Add test for handling NULL values in PostgreSQL connector
qgis/QGIS pull request #33341
Opened 2019-12-11 15:51 UTC by strk

See https://github.com/qgis/QGIS/pull/33225#issuecomment-564446756

2019-12-11 16:11 UTC, elpaso commented on tests/src/python/test_qgsproviderconnection_postgres.py
> +    def test_true_false(self):
```suggestion
    def test_nulls(self):
```

2019-12-11 16:11 UTC, elpaso requested changes
change the test name or it will shadow the previous one

2019-12-11 16:33 UTC, strk commented
OOps, force-pushed a fix

2019-12-11 16:34 UTC, elpaso approved these changes

2019-12-12 08:25 UTC, strk commented
@elpaso the tests indeed fail:
https://travis-ci.org/qgis/QGIS/jobs/623752437#L2455-L2471

Those NULL values are returned as False instead of None

2019-12-12 08:25 UTC, strk commented
(but only for the bool case?)

2019-12-12 13:13 UTC, strk commented
Is it ok to merge with a failing Azure pipeline ? (seems to be)

2019-12-12 13:18 UTC, merged