Don't offer to overwrite whole file on container formats
qgis/QGIS pull request #34817
Opened 2020-03-02 10:38 UTC by uclaros

## Description
Removed the dangerous option to delete the whole container file (geopackage, spatialite etc) when it contains a layer with the same name as the one the user is trying to save.

Fixes  #32823

2020-03-02 12:50 UTC, roya0045 commented
I wouldn't vouch for removing this option, the only thing that I would do is add a dialog asking for confirmation.

2020-03-02 12:54 UTC, 3nids commented
To me, it's the very first message which is problematic.
When you select an existing file, it says it is going to be overwritten even when your intention is to add a layer to it.

I think we should have a radio button on top of the dialog, letting the choice between: "create/overwrite GPGK" and "add layer to existing GPKG".

That would remove any confusion, and bonus, you won't get a warning when you select an existing file in the dialog.

2020-03-02 13:44 UTC, uclaros commented
> When you select an existing file, it says it is going to be overwritten even when your intention is to add a layer to it.

No, it does not. It just saves the new layer in the existing geopackage.

Imagine the exact equivalent to the *Overwrite File* option when saving for example a spreadsheet:
You get a dialog saying *File spreadsheet.xls already exists. Do you want to overwrite it, or do you want to overwrite it and then also delete all other files (regardless of their format) that exist in the same folder?*
This does not exist in any software because it just makes no sense. If the user wants to delete the folder (or geopackage) he can do it explicitly in the file selection dialog while selecting the filename and seeing that it already exists.

An ideal solution for me would be to be able to browse the geopackage contents like it was a folder, in the file selection dialog. Then the user would already be aware of the geopackage contents and in a better position to decide the name of the layer to choose or if he wants to delete the geopackage and all it's contents. But that is probably too much work.

2020-03-02 13:48 UTC, nirvn commented
-1 to remove a feature here. If wording is not clear enough, we can update that. I personally use file overwrite quite often. 

Not offering this option also means ppl might end up adding a layer to a preexisting gpkg without realizing it, and potentially share sensitive data by mistake.

2020-03-02 13:55 UTC, uclaros commented
> Not offering this option also means ppl might end up adding a layer to a preexisting gpkg without realizing it, and potentially share sensitive data by mistake.

This may already be happening, since the dialog appears only on layer collision, not on filename collision.

2020-03-02 14:14 UTC, 3nids commented
> No, it does not. It just saves the new layer in the existing geopackage.

Then this is really misleading:

![Screen Recording 2020-03-02 at 15 07 57](https://user-images.githubusercontent.com/127259/75684046-69eac780-5c98-11ea-9fac-18cb29943c76.gif)

2020-03-02 14:35 UTC, uclaros commented
Is this an OSX thing? In my build this does not pop up, neither with the *New Geopackage Layer* nor with the *Save Vector Layer As...* dialogs.

QGIS version | 3.13.0-Master | QGIS code revision | 09fb04d732
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Debian 12.2-1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Debian GNU/Linux bullseye/sid | This copy of QGIS writes debugging output.
Active python plugins | firstaid; plugin_reloader; openlayers_plugin; QuickWKT; StreetView; FreehandRasterGeoreferencer; processing; db_manager

2020-03-02 21:17 UTC, nyalldawson commented
I'm with @nirvn here, I'm -1 to removing the option and think we just need extra confirmation/warning prompts instead.

2020-03-08 13:30 UTC, uclaros commented
Added a warning with the layers that the user is about to say goodbye to. It should not spawn when the file has only one layer (ie Overwrite file and overwrite layer will have the same effect) so the user does not get used to it and clicks OK without thinking. It only spawns when other layers are going to be deleted.
I also have the following thoughts that bother me:
1. Is my use of `QgsOgrLayerItem::subLayers()` proper for the occasion or should I have looked elsewhere?
2. Am I wrong or the file has been opened three times, once for `QgsVectorFileWriter::editionCapabilities()`, once for `QgsVectorFileWriter::targetLayerExists()` and once for `QgsOgrLayerItem::subLayers()`? Should this be optimized?
3. I don't like that I had to copy paste the same code in 3 places in the same file. Wouldn't it be better to create a single message box for all capabilities cases and only add the proper buttons depending on the case?
4. This has to be applied to at least `qgsnewgeopackagelayerdialog.cpp` and `qgsnewspatialitelayerdialog.cpp`, maybe more places. There's a lot of duplicate code there that can lead to inconsistencies (like the new shapefile dialog has radio buttons for Z/M values, while the geopackage and spatialite have chackboxes). Wouldn't it be better to have a `QgsNew*LayerDialog` that handles such stuff centrally and subclass it for each format? Even more, have a base class that both `QgsVectorLayerSaveAsDialog` and `QgsNew*LayerDialog` could use?

2020-03-22 16:51 UTC, uclaros commented
This is what the new warning dialog looks like:
![Screenshot_20200322_184906](https://user-images.githubusercontent.com/11358178/77255144-ff60f200-6c6d-11ea-92ee-4c06207949f8.png)

2020-03-22 21:33 UTC, roya0045 commented
> This is what the new warning dialog looks like:
> ![Screenshot_20200322_184906](https://user-images.githubusercontent.com/11358178/77255144-ff60f200-6c6d-11ea-92ee-4c06207949f8.png)

I can get behind this.

2020-04-01 22:20 UTC, roya0045 commented
@uclaros what happens when the layer list is too big, does the ok gets out of the screen or can there be a text box with a scroll bar in that case?

2020-04-01 23:06 UTC, uclaros commented
This is a generic `QMessageBox::warning` so it will probably grow with the contents and push the buttons out of the screen, indeed. Maybe I could put the layers list into `detailedText` which requires pressing a *show details* button and display a scrollable text box.

2020-04-04 14:42 UTC, uclaros commented
I restructured the code to avoid all the duplicate code in each capability case.

As for the overwrite whole file confirmation, it now looks like this:
![Peek 2020-04-04 17-32](https://user-images.githubusercontent.com/11358178/78453568-45b94680-769b-11ea-845e-2c955a63cd61.gif)

It still only spawns when there is more than one layer on the file to be overwritten.

2020-04-04 22:18 UTC, nyalldawson commented
@uclaros I like that!

(off topic: why are your layers named .shp? :smile: )

2020-04-05 15:16 UTC, uclaros commented
> (off topic: why are your layers named .shp? smile )

@nyalldawson They were merged in a geopackage with some ad-hoc ogr2ogr bash script but didn't bother to trim the extension! Apparently Greece still lives in the age of .shp and .mdb!

2020-04-07 22:40 UTC, nyalldawson requested changes
Looking good! Just some minor cleanups left...

2020-04-07 22:40 UTC, nyalldawson commented on src/gui/ogr/qgsvectorlayersaveasdialog.cpp
> +                                  tr( "The existing layer has different fields. Do you want to add the missing fields to the layer?" ) ) == QMessageBox::Yes )
```suggestion
                                  tr( "The existing layer has additional fields. Do you want to add the missing fields to the layer?" ) ) == QMessageBox::Yes )
```

2020-04-07 22:40 UTC, nyalldawson commented on src/gui/ogr/qgsvectorlayersaveasdialog.cpp
> +    const QList<QgsOgrDbLayerInfo *> subLayers = QgsOgrLayerItem::subLayers( filename(), format() );
This is leaked - the entries need to be deleted

2020-04-07 22:40 UTC, nyalldawson commented on src/gui/ogr/qgsvectorlayersaveasdialog.cpp
> +    QStringList layerList = QStringList();
```suggestion
    QStringList layerList;
```

2020-04-07 22:40 UTC, nyalldawson commented on src/gui/ogr/qgsvectorlayersaveasdialog.cpp
> +    for ( const auto layer : subLayers )
```suggestion
    for ( const QgsOgrDbLayerInfo* layer : subLayers )
```

2020-04-07 22:40 UTC, nyalldawson commented on src/gui/ogr/qgsvectorlayersaveasdialog.cpp
> +      msgBox.setWindowTitle( tr( "Overwrite file" ) );
```suggestion
      msgBox.setWindowTitle( tr( "Overwrite File" ) );
```

2020-04-07 22:41 UTC, nyalldawson commented
(I think we should backport this to LTR)

2020-04-07 22:44 UTC, roya0045 commented
@uclaros nice UI improvement on the dialog!

2020-04-12 21:37 UTC, merged