Add expression functions for arrays and maps
qgis/QGIS pull request #3500
Opened 2016-09-16 06:09 UTC by pvalsecc

2016-09-16 06:16 UTC, nyalldawson commented
Awesome - this makes me very excited!

2016-09-16 06:17 UTC, nyalldawson commented on resources/function_help/json/array_concat
> +  "name": "array_concat",
This is differing from Postgres' naming ("array_cat"). Not sure if that's an issue or not - personally I prefer your "array_concat".

2016-09-16 06:20 UTC, nyalldawson commented on src/core/qgsexpression.cpp
> +  return values.at( 0 ).toList().length();
It'd be a good idea to protect these conversions with a similar function to the existing getIntValue/getDoubleValue/etc, and set the eval error string to notify users if they use a non-list value with these functions.

2016-09-16 06:21 UTC, nyalldawson commented on src/core/qgsexpression.cpp
> +  const int pos = values.at( 1 ).toInt();
these should use getIntValue

2016-09-16 06:22 UTC, nyalldawson commented on tests/src/core/testqgsexpression.cpp
> +    }
I'd like to see some tests here where the array/map functions are called with non array/map values

2016-09-16 06:28 UTC, nyalldawson requested changes
Very very comprehensive PR - great work! Two things which I was thinking after looking over this:
- what do you think about adding an "array_intersects(a,b)" function which would return true if an any element of a exists in b?
- do you think there's any value in having a way of writing an array literal, eg "[2,3,4]"? I'm happy to have a go at this (I really enjoy working with the lexer now!) unless you think it adds no value over the `array(a,b)` function. 

This looks fantastic... it opens up stacks of possibilities. I'm already thinking an array aggregate function, array to multigeom, split string to array, array to string (with concatenator),...

2016-09-16 06:40 UTC, pvalsecc commented on resources/function_help/json/array_concat
> +  "name": "array_concat",
I've been asked to match the postgres function names. Mistake on my side. I'll change it.

2016-09-16 06:45 UTC, nyalldawson commented
Another cool thing we could do:

` apply(@element * 2, array(1,2,3) ) ` ->2, 4, 6

2016-09-16 06:58 UTC, nirvn commented
@pvalsecc , nice!

It'd be useful to be able to create arrays and maps out of a string; that way, an array or map could be created out of a string field.

For e.g, if you open an .osm (openstreetmap file format) in QGIS, there's an other_tag field which adds additional osm tags that aren't mapped out by ogr using a string: 
"access"=>"yes","bicycle"=>"yes","cycleway"=>"no","foot"=>"yes","maxspeed"=>"30","oneway"=>"no","surface"=>"asphalt"

We could then do stuff like: map_get(map("other_tags"),oneway)

2016-09-16 07:21 UTC, nyalldawson commented
(thinking aloud) another useful function would be `range(min,max,step),` which returns an array

2016-09-16 07:39 UTC, pvalsecc commented
OK, I've fixed all the comments but the ones asking for additional functions (except array_intersect).

For the other functions, they can be added later. Otherwise this PR will just keep growing with people's requests.

For the string parsing, there are so many formats out there to represent maps and arrays, that will require a good reflection before starting.

2016-09-16 07:45 UTC, nyalldawson commented
Agreed about not adding extra functions here - the list would be endless ;)

2016-09-16 07:47 UTC, pvalsecc commented
@nirvn,

Wouldn't it be better to change the stuff that reads .osm to import the "other_tags" column as a QVariantMap? Like I did for postgres and spatialite?

2016-09-16 07:49 UTC, nirvn commented
@pvalsecc , sure, it'd be fantastic if that's possible.

2016-09-16 07:51 UTC, rouault commented
> Wouldn't it be better to change the stuff that reads .osm to import the "other_tags" column as a QVariantMap? Like I did for postgres and spatialite?

FYI, the "stuff" in that instance if the OGR OSM driver ;-). There's no string map type currently in OGR. Hence this serialization as a Postgres HSTORE

2016-09-17 04:04 UTC, nyalldawson commented on src/core/qgsexpression.cpp
>      ;
These new functions must also be added to QgsExpression::BuiltinFunctions

2016-09-17 04:06 UTC, nyalldawson commented
Sorry - one last change noted above

2016-09-17 06:11 UTC, pvalsecc commented on src/core/qgsexpression.cpp
>      ;
Can't this list be built in this function based on the `StaticFunction`s we add in there?
I'll have a look Thursday. 3 days weekend, here.

2016-09-20 12:20 UTC, pvalsecc commented
@nyalldawson, I've gone a bit freestyle for fixing the `BuiltinFunctions` problem.
Fixes the missing functions in the list.

2016-09-20 20:54 UTC, merged

2016-09-20 20:54 UTC, nyalldawson commented
Looks great! Any objections if I backport these 2 commits to master_2? (just the expression stuff, not the provider or widget changes)

2016-09-21 05:25 UTC, pvalsecc commented
> Any objections if I backport these 2 commits to master_2? (just the expression stuff, not the provider or widget changes)

No problem backport whatever you see fit.