Refresh filtered features in Attribute Table on data change
qgis/QGIS pull request #35034
Opened 2020-03-12 14:09 UTC by signedav

Like e.g. on adding or removing features.

Since the list of filtered features is created in the widget this function has to be called.

2020-03-16 14:13 UTC, elpaso requested changes

2020-03-16 14:13 UTC, elpaso commented on src/gui/attributetable/qgsattributetablefiltermodel.cpp
> +  QgsDistanceArea myDa;
```suggestion
  QgsDistanceArea distanceArea;
```

2020-03-16 14:13 UTC, elpaso commented on src/gui/attributetable/qgsattributetablefiltermodel.cpp
> +  bool fetchGeom = mFilterExpression.needsGeometry();
```suggestion
  const bool fetchGeom = mFilterExpression.needsGeometry();
```

2020-03-16 14:13 UTC, elpaso commented on src/gui/attributetable/qgsattributetablefiltermodel.h
> +    void setFilterExpression( const QgsExpression &expression, const QgsExpressionContext &context ) { mFilterExpression = expression; mFilterExpressionContext = context; }
move to cpp file and add missing docs for context

2020-03-16 14:13 UTC, elpaso commented on src/gui/attributetable/qgsattributetablefiltermodel.h
> +    void filterFeatures();
missing docs

2020-03-16 14:13 UTC, elpaso commented on src/gui/attributetable/qgsattributetablefiltermodel.h
> +     * the master table model changes.
```suggestion
     * the master table model change.
```

2020-03-16 14:13 UTC, elpaso commented on src/gui/attributetable/qgsfeaturelistview.h
> +     * Emmits the signal for the feature and the selection information
```suggestion
     * Emits the signal for the feature and the selection information
```

2020-03-16 16:22 UTC, signedav commented
Thanks @elpaso I added a small test as well...

2020-03-17 21:04 UTC, signedav commented
What do you think about a backport @elpaso It's imho a bugfix, but not critical...

2020-03-23 12:09 UTC, signedav commented
@elpaso is this good to merge?

2020-03-26 07:47 UTC, merged