Vertex tool, fix escape to stop dragging edge
qgis/QGIS pull request #36587
Opened 2020-05-20 18:12 UTC by uclaros

## Description
In vertex tool, dragging a vertex can be stopped by pressing Escape, but dragging an edge cannot. This PR fixes that, so escape can stop both dragging a vertex or an edge.

2020-05-20 21:33 UTC, nyalldawson approved these changes

2020-05-20 21:35 UTC, nyalldawson requested changes
Actually there's additional code paths which need updating here now - eg the non-escape key presses should only apply when mDraggingEdge is false

2020-05-21 07:53 UTC, uclaros commented
I restructured it into a switch statement, the code paths are less cryptic now.
Also fixes the case where one could `highlightAdjacentVertex()` while dragging vertices.
`highlightAdjacentVertex()` handles the case of `mSelectedVertices.isEmpty()` that's why I omitted it.

2020-05-21 23:22 UTC, nyalldawson approved these changes

2020-05-21 23:22 UTC, merged