[FEATURE] add a replace_array() expression
qgis/QGIS pull request #3670
Opened 2016-10-25 07:43 UTC by nirvn

Simple string function addition to QGIS' expression engine that makes use of the (extremely cool) recent array support addition.

This new string function allows you to modify a string by replacing matching array of strings with either an array of strings or a single string replacement. It can clean up expression that relies in a cascade of replace() calls (i.e. replace(replace(replace(‘boring’)))) .

For e.g., a simple expression to convert numbers from latin to Khmer: 

`replace_array(my_number,array(‘1’,‘2’,‘3’,‘4’,‘5’,‘6’,‘7’,‘8’,‘9’,’0’),array(‘១’,‘២’,‘៣’,‘៤’,‘៥’,‘៦’,‘៧’,‘៨’,‘៩’,’០’))`

Going from 10 replace() to a single replace_array() is a nice win.

2016-10-25 08:08 UTC, nirvn commented
@nyalldawson , your review would be appreciated/needed.

2016-10-25 08:48 UTC, nyalldawson requested changes
What do you think about instead modifying the existing replace method to detect array arguments? I'd suggest this is a nicer approach. You could even allow an array for the second argument and a single value for the third to replace any of the listed values with the single replacement.

2016-10-25 08:48 UTC, nyalldawson commented on tests/src/core/testqgsexpression.cpp
> +      QTest::newRow( "replace_array (array replaced by array)" ) << "replace_array('321', array('1','2','3'), array('7','8','9'))" << false << QVariant( "987" );
Can you add tests with unbalanced array lengths? Ie one with before > after, and vice versa.

2016-10-25 09:44 UTC, nirvn commented
@nyalldawson 

- [x] I've upgraded replace() instead of creating a new function, glad you suggested that
- [x] the additional invalid tests have been added

Thanks for the quick review.

2016-10-25 14:05 UTC, DelazJ commented on resources/function_help/json/replace
> +                { "expression":"replace_array('QGIS ABC',array('A','B','C'),array('X','Y','Z'))", "returns":"'QGIS XYZ'"},
replace_array left here and below

2016-10-25 14:05 UTC, DelazJ commented on resources/function_help/json/replace
> +  "description": "Returns a string with the the supplied string or array of strings replaced by a string or an array of strings.",
typo: the the

2016-10-25 14:32 UTC, m-kuhn commented
Wasn't map support added as well? I think that would make it even easier to read and maintain such lists.

2016-10-26 01:51 UTC, nirvn commented
@DelazJ , thanks for spotting those mistake, the updated commit fixed those.

@m-kuhn , I don't think map would have worked here, especially not now that we've gone down the road of upgrading the replace() function. Relying on a map object would have made it impossible to do replace an array of strings by a single string, i.e. replace('my string','array('y','n','g','etc'),'').

2016-10-26 08:19 UTC, m-kuhn commented
@nirvn I was mostly thinking of

```
replace( my_number,
  map('1', '១',
      '2', '២',
	  '3', '៣',
	  '4', '៤',
	  '5', '៥',
	  '6', '៦',
	  '7', '៧',
	  '8', '៨',
	  '9', '៩',
	  '0', '០')
)
```

I think they can live side-by-side?

2016-10-26 10:43 UTC, nirvn commented
@m-kuhn , something like what I've just committed to this PR? :)

2016-10-26 10:50 UTC, m-kuhn commented
Good job!

2016-10-26 10:57 UTC, nyalldawson commented on src/core/qgsexpression.cpp
> +    parent->setEvalErrorString( QObject::tr( "Function make_point requires 2 or 3 arguments" ) );
make_point -> replace

2016-10-26 10:57 UTC, nyalldawson commented on resources/function_help/json/replace
> +  "description": "Returns a string with the supplied string or array of strings replaced by a string or an array of strings. The function can also work with two arguments, whereas the second argument
Have a look at the "length" function help - that's a good example how variants such be handled for functions.

2016-10-26 10:58 UTC, nyalldawson commented
Very nice!

2016-10-27 04:36 UTC, nirvn commented
@nyalldawson , done.

2016-10-27 05:15 UTC, merged

2016-10-27 05:15 UTC, nyalldawson commented
Fantastic stuff!

2016-10-27 05:18 UTC, nirvn commented
@nyalldawson , @m-kuhn , thanks for the review / improvement suggestions.