Remove txt2tags dependency (use markdown instead)
qgis/QGIS pull request #36966
Opened 2020-06-04 09:24 UTC by PeterPetrik

follow up from discussion on https://github.com/qgis/QGIS/pull/35914

```
pandoc -o doc/NEWS.html NEWS.md 
pandoc -o doc/INSTALL.html INSTALL.md 
```

Need to update these scripts
- [ ] ./scripts/release.pl
- [ ] ./scripts/update_news.pl

2020-06-04 09:27 UTC, PeterPetrik commented
cc @timlinux

2020-06-04 11:33 UTC, m-kuhn commented
Good move !

Do we still want/need HTML in the source code?

2020-06-04 12:44 UTC, PeterPetrik commented
> Do we still want/need HTML in the source code?

I do not know, it is packaged in some release scripts so I hope @jef-n can say if we need them? Also it looks like that the NEWS is appended automatically, so I am not sure how to do it in this new format...

2020-06-04 16:19 UTC, Codym48 reviewed
This is great! I suggested some hierarchical changes in the Windows workflow, but really appreciate you making the time to convert this to .md!

2020-06-04 22:39 UTC, nyalldawson commented
Great move!

2020-06-05 12:18 UTC, PeterPetrik commented
@jef-n removed INSTALL.html and modified those 3 perl scripts with the new stuff. 

Unfortunately I never used them , and Perl is not my daily bread, so I am wondering if you can take a look if you are happy with the new implementation?

2020-06-05 12:20 UTC, PeterPetrik commented
NEWS.html is used in the QGIS desktop panel so we need to maintain it

2020-06-05 12:46 UTC, m-kuhn commented
> NEWS.html is used in the QGIS desktop panel so we need to maintain it

Ideally this would be created on build (and not stored in git), but this is nowhere close a blocker for this pull request.

2020-06-05 15:42 UTC, Codym48 requested changes

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +   4. [Building on Windows](#3-building-on-windows)
```suggestion
   4. [Building on Windows](#4-building-on-windows)
```

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +   5. [Building on MacOS X](#4-building-on-macos-x)
```suggestion
   5. [Building on MacOS X](#5-building-on-macos-x)
```

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +### 4.1.5. Packaging
```suggestion
### 4.1.6. Packaging
```

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +### 4.1.6. Packaging your own build of QGIS
```suggestion
### 4.1.7. Packaging your own build of QGIS
```

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +### 4.1.7. Osgeo4w packaging
```suggestion
### 4.1.8. Osgeo4w packaging
```

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +### 4.1.4. Setting up the Visual Studio project with CMake
```suggestion
### 4.1.4. Configure and build with CMake from command line
```

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +Running QGIS from within MSVC:
I think a header section here would be worthwhile for consistency with 4.1.4.1 and 4.1.4.2

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +  `C:\OSGeo4W64\QGIS\ms-windows\osgeo4w\build-qgis-test-x86_64\qgis.sln`
```suggestion
  `C:\OSGeo4W64\QGIS\ms-windows\osgeo4w\build-qgis-test-x86_64\qgis.sln`.
```

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +  Edit the properties of the project ALL_BUILD:
```suggestion
  Edit the properties of the project ALL_BUILD to include the path to the executable:
```

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +  Run: Debug -> Start Debugging (F5) or Start Without Debugging (Ctrl+F5)
```suggestion
  To run, use the menu commands: Debug -> Start Debugging (F5) or Start Without Debugging (Ctrl+F5).
```

2020-06-05 15:42 UTC, Codym48 commented on INSTALL.md
> +  Debugging -> Command -> `C:\OSGeo4W64\QGIS\ms-windows\osgeo4w\build-qgis-test-x86_64\output\bin\RelWithDebInfo\qgis.exe`
```suggestion
  Debugging -> Command -> `C:\OSGeo4W64\QGIS\ms-windows\osgeo4w\build-qgis-test-x86_64\output\bin\RelWithDebInfo\qgis.exe`.
```

2020-06-05 15:57 UTC, Codym48 commented
Could also update the **Building from Source** section [at the bottom of the README.md](https://github.com/PeterPetrik/QGIS/blob/remove_txt2txt/README.md#building-from-source) to point to the new INSTALL.md? (It currently references doc/INSTALL.html which won't exist anymore.)

Could also update the text or links in this **Note** [in the README.md](https://github.com/PeterPetrik/QGIS/blob/remove_txt2txt/README.md#note) that mentions the "installation documentation," but actually refers to the [overall documentation webpage](https://qgis.org/en/docs/index.html), and mentions a PDF file in the doc directory that doesn't exist.

2020-06-08 06:04 UTC, PeterPetrik commented
@Codym48 thanks for review. 

At this point I would like to merge this somehow to master (after @jef-n maybe can verify/fix the perl scripts), so such improvement to the text could be done in separate pull requests...

2020-06-08 14:03 UTC, Codym48 approved these changes

2020-06-10 00:00 UTC, nyalldawson commented
Lets go ahead and merge -- it'll be easier to identify any issues in the scripts post merge...

2020-06-10 00:00 UTC, merged