Apply some @m-kuhn comments
qgis/QGIS pull request #3736
Opened 2016-11-08 08:34 UTC by sbrunner

on the commit bc1ad2ce82196402ffa83118b7fd3c2f195a4414

2016-11-08 12:29 UTC, m-kuhn requested changes

2016-11-08 12:29 UTC, m-kuhn commented on src/providers/wfs/qgswfsprovider.h
> +    virtual QVariantMap metadata();
Shouldn't these methods override the one in the base class?

    virtual QVariantMap metadata() const override;

2016-11-08 12:29 UTC, m-kuhn commented
Thanks, that looks a lot better to me!

2016-11-08 12:31 UTC, m-kuhn requested changes

2016-11-08 12:31 UTC, m-kuhn commented on python/core/qgsvectordataprovider.sip
> +    virtual QString translatedMetadataKey( QString md_key ) const;
* Imperatively call it translateMetadataKey() and translateMetadataValue() (they are more transformers than getters)
* pass a `const QString& mdKey ` as parameter

2016-11-08 13:54 UTC, sbrunner commented on python/core/qgsvectordataprovider.sip
> +    virtual QString translatedMetadataKey( QString md_key ) const;
+1

2016-11-08 22:16 UTC, merged

2016-11-09 12:23 UTC, sbrunner commented
Thanks @m-kuhn :-)