Don't delete QgsSymbolSelectorWidget symbol when widget is closed
qgis/QGIS pull request #38921
Opened 2020-09-21 16:51 UTC by troopa81

## Description

Fixes #38920 :  Don't delete the symbol without deleting the widget. The widget is still connected to some signals (see constructor) and try to access the deleting symbol in slot method. The widget and the symbol will be deleted by QgsPanelWidgetStack::closePanel (panel has autoDelete flag)

2020-09-21 17:58 UTC, m-kuhn approved these changes
Ownership documentation of the functions as well as unique_ptr-wise reflect the suggestions of this PR.
I wonder how this went by unnoticed for so long.

2020-09-21 22:24 UTC, nyalldawson commented
I don't think this is correct -- from the documentation for QgsSymbolSelectorWidget:

    "\note The ownership of the symbol is not transferred and must exist for the lifetime of the widget."

In QgsSymbolButton::showSettingsDialog() we create a new symbol via

    QgsSymbol *newSymbol = mSymbol->clone();

and then create the selector widget using this symbol (ownership is NOT transferred):

    QgsSymbolSelectorWidget *d = new QgsSymbolSelectorWidget( newSymbol, QgsStyle::defaultStyle(), mLayer, nullptr );

so the widget's symbol is STILL owned by the QgsSymbolButton. With this PR there's nothing cleaning up the symbol, so there's a leak.

I admit this is all disgusting memory management, but I can't see any alternative which doesn't break the (bad) api for QgsSymbolSelectorWidget which has been around since 2.x. QgsSymbolSelectorWidget should really take a clone of the symbol and drop the requirement that the symbol pointer exists for the lifetime of the widget... (TODO for 4.0, there's already a note in the code to this effect)

2020-09-21 22:25 UTC, nyalldawson commented
(also note that this same code logic exists in many places, e.g. QgsCategorizedSymbolRendererWidget,...)

2020-09-21 23:07 UTC, nyalldawson commented
Alternative fix https://github.com/qgis/QGIS/pull/38928

2020-09-22 05:26 UTC, m-kuhn commented
Thanks for looking closer @nyalldawson I was misled by the local std::unique_ptr and missed the case that in the dock widget scenario the memory management is ... counter intuitive.

2020-09-22 05:27 UTC, m-kuhn requested changes
Leaks

2020-09-22 05:57 UTC, closed without merging