[BUGFIX][Server] WMS compliance: stretched, distort, increase, decrease
qgis/QGIS pull request #3906
Opened 2016-12-26 12:58 UTC by rldhont

The commit d44f1eba2fed18b3fef8d8865d79b3b6d8bc4d69 seems to break some WMS 1.3.0 client and WMS compliancy.
The commit d44f1eba2fed18b3fef8d8865d79b3b6d8bc4d69 has been written to fix an issue with QGIS WMS Client and to render image like other WMS Server.

This commit has been written to fix issue introduce by d44f1eba2fed18b3fef8d8865d79b3b6d8bc4d69.
It is based on MapServer code:
* https://github.com/mapserver/mapserver/blob/master/mapdraw.c#L115
* https://github.com/mapserver/mapserver/blob/master/HISTORY.TXT#L3768

2016-12-26 18:58 UTC, nyalldawson commented
Since this seems to be a tricky calculation I'd suggest adding unit tests to protect this logic.

2016-12-26 21:00 UTC, rldhont commented
@nyalldawson, this commit comes from this discussion https://github.com/qgis/QGIS/commit/d44f1eba2fed18b3fef8d8865d79b3b6d8bc4d69#commitcomment-20259007
Tests has to be updated but unit test are not enough. We need to verify that QGIS WMS client and other WMS client are not broken.

2016-12-30 09:10 UTC, mhugent commented
As the ms calculation uses a mixture of both ratios, I don't think it is 100% correct.
But it does not matter. The image distortion is IMHO a bad idea of the OGC spec. We should disable it completely or use the ms calculation in this PR to not have any troubles with WMS clients.

2017-01-02 10:49 UTC, rldhont commented
Thanks @mhugent 

@elpaso can you test this PR ?

2017-01-02 11:32 UTC, elpaso commented
@rldhont you read my mind, I've just built your branch ... :)

2017-01-02 16:59 UTC, elpaso commented
@rldhont tested this PR with QGIS server and QGIS client and there is exactly the same problem we noticed in Lyon, in the attached image you can see the same layer (world shapefile EPSG:4326) rendered directly into QGIS (grey outline) and served through QGIS Server (the coloured polygons).
You can see how the grey outline is the correct one.
![stretch_error](https://cloud.githubusercontent.com/assets/142164/21593197/b97010ca-d114-11e6-805e-46eef23f4314.png)

2017-01-02 17:52 UTC, elpaso requested changes
@rldhont, I've tested master again without this PR and it seems to me the right behavior. This PR re-introduces the bug that we've seen in Lyon.

2017-01-02 19:46 UTC, rldhont commented
hi @elpaso, can you provide the URL to the data and the URL generated by QGIS desktop to reprodiuce the issue?

2017-01-02 19:53 UTC, rldhont commented
@mhugent can you provide some example which describe the issue with openlayers that @pka has explain on Twitter?

2017-01-02 19:58 UTC, elpaso commented
@rldhont  you can easily reproduce it:

1. create a QGIS project with a single shapefile layer EPSG:4326 whole world
2. serve that project through QGIS Server

then ...

1. open QGIS and load the EPSG:4326 whole world shapefile layer directly inside QGIS
2. add the WMS layer created in the previous steps.
3. enjoy the difference

I checked the QGIS Desktop created URLs and they seems correct: both the BBOX and 
HEIGHT/WIDTH seem correct.

Example URL generated by QGIS WMS provider (untiled):
`?MAP=/opt/qgis-server/projects/world_qt5.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-40.42095738741319622,-189,71.67899928492427364,189&CRS=EPSG:4326&WIDTH=1046&HEIGHT=310&LAYERS=world&STYLES=&FORMAT=image/jpeg&DPI=220&MAP_RESOLUTION=220&FORMAT_OPTIONS=dpi:220`


See what happens here with current master (not your PR):
![immagine](https://cloud.githubusercontent.com/assets/142164/21595406/e8994e16-d12d-11e6-81e7-055701f20da3.png)

See what happens with your PR (same call):
![immagine](https://cloud.githubusercontent.com/assets/142164/21595413/000b70f6-d12e-11e6-9211-d280e6d1ec17.png)

2017-01-02 20:07 UTC, rldhont commented
@elpaso thanks!
@mhugent any idea about the difference?

2017-01-03 07:41 UTC, sbrunner reviewed
Why should we change the width and height, shouldn't they simply be unchanged?

2017-01-03 08:32 UTC, rldhont commented
@sbrunner the image has to be stretched by the server to be WMS 1.3.0 compliant

2017-01-03 08:52 UTC, sbrunner commented
I don't see that's scaled back here: https://github.com/rldhont/Quantum-GIS/blob/48835dd6f7fbc4a13fe1e598652cbffa7ab45380/src/server/qgswmsserver.cpp#L1496

2017-01-03 09:28 UTC, rldhont commented
@mhugent and @elpaso this issue is due to the fact that the image ratio does not take account of the Change x- and y- of BBOX for WMS 1.3.0 if axis inverted.

I'll enhance the code to do so!

2017-01-03 10:59 UTC, sbrunner commented on src/server/qgswmsserver.cpp
> +      mapExtent.invert();
Don't you have unwanted double invert? (with the line 1991)

2017-01-03 11:00 UTC, rldhont commented
@elpaso and @mhugent the code has been updated to take account of axis invertion.

So with a world countries data we have:
![world_countrie](https://cloud.githubusercontent.com/assets/1575538/21605816/c4d42662-d1ab-11e6-9f01-a8607b0a7992.jpeg)
`SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-40.42095738741319622,-189,71.67899928492427364,189&CRS=EPSG:4326&WIDTH=1046&HEIGHT=310&LAYERS=countries&STYLES=&FORMAT=image/jpeg&DPI=220&MAP_RESOLUTION=220&FORMAT_OPTIONS=dpi:220`

And I have tested with the OGC CITE ratio-aspect request and we have:
without stretched
![cite-wms-aspect-ratio](https://cloud.githubusercontent.com/assets/1575538/21605845/0d7e084c-d1ac-11e6-8f70-c2d81b221fbd.jpeg)
`SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=cite:Streams,cite:Lakes,cite:Ponds,cite:Bridges,cite:RoadSegments,cite:DividedRoutes,cite:Buildings,cite:MapNeatline&STYLES=&CRS=CRS:84&BBOX=-0.005,-0.0025,0.005,0.0025&WIDTH=200&HEIGHT=100&FORMAT=image/jpeg`
with stretched
![cite-wms-aspect-ratio-stretched](https://cloud.githubusercontent.com/assets/1575538/21605854/226a6638-d1ac-11e6-81e5-10c68ee9f023.jpeg)
`SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=cite:Streams,cite:Lakes,cite:Ponds,cite:Bridges,cite:RoadSegments,cite:DividedRoutes,cite:Buildings,cite:MapNeatline&STYLES=&CRS=CRS:84&BBOX=-0.005,-0.0025,0.005,0.0025&WIDTH=200&HEIGHT=200&FORMAT=image/jpeg`

Are you agree with the code now ?

2017-01-03 11:02 UTC, rldhont commented on src/server/qgswmsserver.cpp
> +      mapExtent.invert();
no crs84 is an invertion of EPSG:4326.
This code has been copy from the copyMapSettings.

2017-01-03 11:05 UTC, sbrunner commented on src/server/qgswmsserver.cpp
> +      mapExtent.invert();
OK, thanks :-)

2017-01-03 11:05 UTC, sbrunner approved these changes

2017-01-03 11:42 UTC, elpaso approved these changes

2017-01-03 11:43 UTC, elpaso commented
@rldhont tested the latest commit and it looks good to me now, it also stretches correctly. Good job!

2017-01-03 14:13 UTC, merged