Show warning when adding more than 1 part to single geometry layers
qgis/QGIS pull request #3983
Opened 2017-01-12 10:45 UTC by tudorbarascu

Hello,

Sometimes you can add a part to a single geometry layer that already has a geom turning it into a multipart.
No error or warning is provided until you save and you have to redo steps if you haven't tried to save immediately and get the provider error.

This provides a warning message so that the user has some feedback before he tries to save so that he can undo changes before saving. 

I thought about the cases when the user can save the multi-geometry into a new  layer or the ones where the geometry is reworked database side and I think the message is more helpful than it is disturbing for these cases.

I am a little bit unsure about this, what do you think?
Thanks!

2017-01-12 13:03 UTC, 3nids requested changes
Map tools have a dedicated signal to display messages,  it would me better to use it.

2017-01-13 10:49 UTC, tudorbarascu commented
Hi and thanks for looking into this.

I tried doing that but from what I could grasp, using the Map tool dedicated signal can only be done if the Map tool action stops; I want the action to continue while emitting a warning.

Have I gotten this wrong?

2017-01-16 06:25 UTC, 3nids commented
Have you tried:

    if (( !vlayer->selectedFeatures()[0].geometry().isEmpty() ) && QgsWkbTypes::isSingleType( vlayerwkbType() ) )
      emit messageEmitted( tr( "Feature geom is single part and you've added more than one" ), QgsMessageBar::WARNING );

2017-01-16 10:54 UTC, tudorbarascu commented
@3nids Thanks for guiding me out.
I tried that in the beginning but it didn't work where I introduced the code.

There's still a special case for Shapefiles with Linestring and Polygon geometries as although they output isSingleType is True they always permit saving as multipart.

2017-01-16 12:32 UTC, 3nids commented on src/app/qgsmaptooladdpart.cpp
> +      if (( !isGeometryEmpty ) && QgsWkbTypes::isSingleType( vlayer->wkbType() ) )
`isGeometryEmpty` is used only here. For the sake of clarity and compactiy, better do directly

     if ((vlayer->selectedFeatures()[0].geometry().isEmpty() ) && QgsWkbTypes::isSingleType( vlayer->wkbType() ) )

2017-01-16 14:50 UTC, tudorbarascu commented on src/app/qgsmaptooladdpart.cpp
> +      if (( !isGeometryEmpty ) && QgsWkbTypes::isSingleType( vlayer->wkbType() ) )
It doesn't work if I do it like that.
This is why I didn't use the dedicated signal from the beginning.
I banged my head around this and the only solution that I see is the current one (I'm a newbie with respect to C++).

2017-01-16 15:07 UTC, 3nids commented on src/app/qgsmaptooladdpart.cpp
> +      if (( !isGeometryEmpty ) && QgsWkbTypes::isSingleType( vlayer->wkbType() ) )
maybe adding the part resets the layer selection.
no worries, let's merge it like this!

2017-01-16 15:07 UTC, 3nids approved these changes

2017-01-16 15:07 UTC, merged