fix GRASS v_net_visibility module
qgis/QGIS pull request #41515
Opened 2021-02-11 18:40 UTC by gioman

Fixes https://github.com/qgis/QGIS/issues/41030

2021-02-13 21:44 UTC, nyalldawson commented
@agiudiceandrea are you happy with this fix?

2021-02-14 08:25 UTC, agiudiceandrea commented
I think it could be better to use QgsProcessingParameterString for the "coordinates" parameter, otherwise it wouldn't be possible to insert the coordinates of more then one point.

2021-02-14 08:27 UTC, agiudiceandrea requested changes

2021-02-14 08:27 UTC, agiudiceandrea commented on python/plugins/processing/algs/grass7/description/v.net.visibility.txt
>  QgsProcessingParameterPoint|coordinates|Coordinates|None|True
```suggestion
QgsProcessingParameterString|coordinates|Coordinates|None|False|True
```

2021-02-14 17:59 UTC, gioman commented
> I think it could be better to use QgsProcessingParameterString for the "coordinates" parameter, otherwise it wouldn't be possible to insert the coordinates of more then one point.

@agiudiceandrea done

2021-02-15 22:54 UTC, merged