Update rasterize.py
qgis/QGIS pull request #41905
Opened 2021-02-27 20:09 UTC by talledodiego

## Description

Included the possibility to use Z of feature to extract burn values

Now the user has the possibility to use the Z of feature to extract burn values.

2021-03-01 03:40 UTC, nyalldawson commented
Looking good! Can you add a test covering this to https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/GdalAlgorithmsRasterTest.py#L1537 please?

2021-03-01 10:46 UTC, talledodiego commented
> Looking good! Can you add a test covering this to https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/GdalAlgorithmsRasterTest.py#L1537 please?

With the last commit, I included the test as requested.

2021-03-01 22:39 UTC, nyalldawson approved these changes

2021-03-01 22:39 UTC, nyalldawson commented
Perfect -- thanks!

2021-03-02 05:31 UTC, nyalldawson commented on python/plugins/processing/tests/GdalAlgorithmsRasterTest.py
> +            self.asserEqual(
```suggestion
            self.assertEqual(
```

2021-03-02 05:31 UTC, nyalldawson commented on python/plugins/processing/tests/GdalAlgorithmsRasterTest.py
> +            self.asserEqual(
```suggestion
            self.assertEqual(
```

2021-03-02 06:56 UTC, nyalldawson commented
Actually the tests are failing -- can you fix?

2021-03-02 07:02 UTC, agiudiceandrea requested changes

2021-03-02 07:02 UTC, agiudiceandrea commented on python/plugins/processing/tests/GdalAlgorithmsRasterTest.py
> +                outdir + '/check.jpg'])
```suggestion
                ['gdal_rasterize',
                 '-l pointsz -3d -ts 0.0 0.0 -ot Float32 -of JPEG ' +
                 sourceZ + ' ' +
                 outdir + '/check.jpg'])
```

2021-03-02 12:47 UTC, talledodiego commented
> Actually the tests are failing -- can you fix?


Maybe a silly question... How can I perform the tests to check in my local repository?
Should be fixed now...

2021-03-02 22:48 UTC, nyalldawson commented
@talledodiego 
>  How can I perform the tests to check in my local repository?

Are you building locally?

2021-03-03 01:16 UTC, merged

2021-03-03 18:58 UTC, talledodiego commented
> @talledodiego
> 
> > How can I perform the tests to check in my local repository?
> 
> Are you building locally?

Actually not, I just modified the python files...