change zoom factor value to percent
qgis/QGIS pull request #4242
Opened 2017-03-09 16:48 UTC by myarjunar

funded by: Kartoza

2017-03-09 17:08 UTC, m-kuhn requested changes
Hey @myarjunar thanks a lot, I think this will make this setting much easier to understand.

I have left some comments, mostly for the coding style we use for consistency with the rest of the codebase.

2017-03-09 17:08 UTC, m-kuhn commented on src/app/qgsoptions.cpp
> +  mSettings->setValue( QStringLiteral( "/qgis/zoom_factor" ), QgsOptions::getZoomFactorValue( spinZoomFactor ) );
No reason to prefix this with `QgsOptions::`

2017-03-09 17:08 UTC, m-kuhn commented on src/app/qgsoptions.h
> +    double getZoomFactorValue( QSpinBox *zoomFactorSpinBox);
We normally don't prefix getters with `get`.

Just call this `zoomFactorValue`

2017-03-09 17:08 UTC, m-kuhn commented on src/app/qgsoptions.cpp
> +void QgsOptions::setZoomFactorValue(QSpinBox *zoomFactorSpinBox)
The spacing is wrong here. You can setup a pre-commit hook as described here https://github.com/qgis/QGIS/blob/master/CONTRIBUTE.md so it's done automatically for you.

2017-03-09 17:08 UTC, m-kuhn commented on src/app/qgsoptions.cpp
> +  if ( zoomFactorSpinBox->value() == zoomFactorSpinBox->minimum() ) return 1.01;
Not sure if that's done by astyl automatically meanwhile. We normally break after every if

    if ( xxx )
      return 1.01;

2017-03-09 17:22 UTC, m-kuhn commented on src/app/qgsoptions.cpp
> +double QgsOptions::getZoomFactorValue( QSpinBox *zoomFactorSpinBox )
I don't think it's required to pass this as a parameter.

This is a class member variable which is available in here anyway. Just use `spinZoomFactor` directly.

2017-03-09 17:38 UTC, myarjunar commented
@m-kuhn thanks for your review :+1:  gonna update my PR

2017-03-09 19:33 UTC, m-kuhn commented
Nice, codewise it looks good to me now.

Something else that I think could increase UX even a bit more is to add a tooltip to the spinbox, that shortly explains what the number does (something like "Specifies the change in zoom level with each move of the mouse wheel. The bigger the number, the faster zooming with the mouse wheel will be." Feel free to improve on this if you want.

2017-03-09 19:36 UTC, nyalldawson commented
Another nice change would be to flip the QSpinBox to a QgsSpinBox, and set the clear value to the default zoom factor. Then you get a handy reset icon embedded in the widget for changing it back to the default value.

2017-03-09 19:56 UTC, m-kuhn approved these changes

2017-03-10 10:11 UTC, merged

2017-03-10 10:11 UTC, m-kuhn commented
Thank you @myarjunar 
Excellent work

2017-03-10 11:57 UTC, myarjunar commented on src/app/qgsoptions.cpp
> +    int percentValue = mSettings->value( QStringLiteral( "/qgis/zoom_factor" ), 2 ).toInt() * 100;
ups I messed up here. it supposed to be `toDouble()`.
gonna create a patch for this.

2017-03-10 11:58 UTC, m-kuhn commented on src/app/qgsoptions.cpp
> +    int percentValue = mSettings->value( QStringLiteral( "/qgis/zoom_factor" ), 2 ).toInt() * 100;
good catch