add grid renderer for points displacement. funded by Kartoza
qgis/QGIS pull request #4255
Opened 2017-03-14 04:00 UTC by myarjunar

## Description
Add new grid points displacement renderer for layer styling. This is based on http://gis.stackexchange.com/questions/227242/convert-stacked-points-into-grid

![qgis 5e21641 - points_displacement_037](https://cloud.githubusercontent.com/assets/11134669/23885386/37c9b760-08a5-11e7-86de-09d5d4b33c26.png)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

2017-03-14 04:07 UTC, NathanW2 commented
oh! Nice!

I assume that we can remove the black lines?

On Tue, Mar 14, 2017 at 2:00 PM, Muhammad Yarjuna Rohmat <
notifications@github.com> wrote:

> Description
>
> Add new grid points displacement renderer for layer styling. This is based
> on http://gis.stackexchange.com/questions/227242/convert-
> stacked-points-into-grid
>
> [image: qgis 5e21641 - points_displacement_037]
> <https://cloud.githubusercontent.com/assets/11134669/23885386/37c9b760-08a5-11e7-86de-09d5d4b33c26.png>
> Checklist
>
> Reviewing is a process done by project maintainers, mostly on a volunteer
> basis. We try to keep the overhead as small as possible and appreciate if
> you help us to do so by completing the following items. Feel free to ask in
> a comment if you have troubles with any of them.
>
>
>    - Commit messages are descriptive and explain the rationale for changes
>    - Commits which fix bugs include fixes #11111 in the commit message
>    next to the description
>    - Commits which add new features are tagged with [FEATURE] in the
>    commit message
>    - Commits which change the UI or existing user workflows are tagged
>    with [needs-docs] in the commit message and containt sufficient
>    information in the commit message to be documented
>    - I have read the QGIS Coding Standards
>    <https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html>
>    and this PR complies with them
>    - This PR passes all existing unit tests (test results will be
>    reported by travis-ci after opening this PR)
>    - New unit tests have been added for core changes
>    - I have run the scripts/prepare-commit.sh script
>    <https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis>
>    before each commit
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/qgis/QGIS/pull/4255
> Commit Summary
>
>    - add grid renderer for points displacement. funded by Kartoza
>
> File Changes
>
>    - *M* src/core/symbology-ng/qgspointdisplacementrenderer.cpp
>    <https://github.com/qgis/QGIS/pull/4255/files#diff-0> (74)
>    - *M* src/core/symbology-ng/qgspointdisplacementrenderer.h
>    <https://github.com/qgis/QGIS/pull/4255/files#diff-1> (8)
>    - *M* src/gui/symbology-ng/qgspointdisplacementrendererwidget.cpp
>    <https://github.com/qgis/QGIS/pull/4255/files#diff-2> (1)
>
> Patch Links:
>
>    - https://github.com/qgis/QGIS/pull/4255.patch
>    - https://github.com/qgis/QGIS/pull/4255.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/qgis/QGIS/pull/4255>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAXS3KqAI9KNgcQqOB5FzRRPSxQEpzozks5rlhDPgaJpZM4McGck>
> .
>

2017-03-14 04:25 UTC, myarjunar commented
@NathanW2 I assumed that black lines acts like the circle line on `ring` or `concentric rings` displacement. or should we just remove the option for creating lines on grid renderer? CMIIW

2017-03-14 04:29 UTC, NathanW2 commented
@myarjunar no I think it's fine to leave it.  We can just set to transparent if needed.

2017-03-14 04:31 UTC, nirvn commented
One nice aspect of the map linked in the stackexchange link is the sorted ordering of the dots. 

I'd be cool to add sorting capability to the points displacement (with ordered placement logic for circles, filled circles, and grid)

2017-03-14 05:01 UTC, nyalldawson requested changes

2017-03-14 05:01 UTC, nyalldawson commented on src/core/symbology-ng/qgspointdisplacementrenderer.cpp
> +        for ( int xIndex = 0; xIndex < gridSize; ++xIndex )
for ( int xIndex = 0; xIndex < gridSize && pointsRemaining > 0; ++xIndex )

otherwise this inner loop runs more times than is necessary

2017-03-14 05:01 UTC, nyalldawson commented on src/core/symbology-ng/qgspointdisplacementrenderer.cpp
> +      double pointRadius = ( centerDiagonal / 2.0 + symbolDiagonal / 2.0 ) + symbolDiagonal;
I'd suggest:

- Change this line to:

      double pointRadius = ( centerDiagonal / 2.0 + symbolDiagonal / 2.0 ) + symbolDiagonal + circleAdditionPainterUnits;

- Change the label for "Ring size adjustment" in the ui to just "Size adjustment"

Then users can tweak the grid spacing as desired. We'll never be able to autocalculate an ideal spacing which works for all symbol types, so it's a good idea to give this control to the user.

2017-03-14 05:01 UTC, nyalldawson commented on src/core/symbology-ng/qgspointdisplacementrenderer.cpp
> +    double shiftAmount = -radius * ( size - 1 ) / 2;
pulling shiftAmount and centralShift out of this loop will prevent calculating them multiple times

2017-03-14 05:01 UTC, nyalldawson commented on src/core/symbology-ng/qgspointdisplacementrenderer.cpp
> +  for ( int pointIndex = 0; pointIndex < pointSymbolPositions.size(); ++pointIndex )
This loop is drawing every inner cell border twice - you can see this by setting a semi-transparent line color and note how the inner borders are darker than the outer ones

2017-03-14 05:01 UTC, nyalldawson commented on src/core/symbology-ng/qgspointdisplacementrenderer.h
> +      Grid //!< Place points in a grid around group
Don't forget to add this one to the sip bindings

2017-03-14 05:03 UTC, nyalldawson commented
@myarjunar Great work! A very nice addition to this renderer.

One last part needed here (apart from the minor comments listed above) - we need to add a unit test covering this new addition. You'd need to add something like testRenderWithin in test_qgspointdisplacementrenderer.py. The render tests can be a bit tricky to work out at first - ping me if you need assistance!

2017-03-14 05:03 UTC, nyalldawson commented
> One nice aspect of the map linked in the stackexchange link is the sorted ordering of the dots.

> I'd be cool to add sorting capability to the points displacement (with ordered placement logic for circles, filled circles, and grid)

That's a different issue, and happens to all displacement modes. Let's tackle that separately ;)

2017-03-14 05:04 UTC, timlinux commented
@myarjunar I think it would be good to add some nicer screenshot to your PR..including comparing existing displacement renderer with your new grid render.

2017-03-14 05:16 UTC, nirvn commented
@nyalldawson , yep, I wasn't suggesting to add this sorting capability to the PR, just highlighting the idea within our collective consciousness ;)

2017-03-14 09:12 UTC, DelazJ commented
Thanks @myarjunar 
And as usual, with my doc writer hat, I'd like to remind that it'd be nice to add a [FEATURE] or [needs-docs] tag in the commit as stated in the PR template, with a bit more description.

> - [ ] Commits which add new features are tagged with [FEATURE] in the commit message
> - [ ] Commits which change the UI or existing user workflows are tagged with [needs-docs] in the commit message and containt sufficient information in the commit message to be documented

2017-03-14 17:42 UTC, myarjunar commented
Requested changes:
- [] change `double pointRadius = ( centerDiagonal / 2.0 + symbolDiagonal / 2.0 ) + symbolDiagonal + circleAdditionPainterUnits;`

- [] Change the label for "Ring size adjustment" in the ui to just "Size adjustment"

- [] Change `for ( int xIndex = 0; xIndex < gridSize && pointsRemaining > 0; ++xIndex )`

- [] Pulling shiftAmount and centralShift out of the loop

- [] Fix drawing every inner cell border twice

- [] Add sip binding

- [] Add unit test

2017-03-29 12:58 UTC, andreasneumann commented
Nice - @myarjunar - definitely a very useful addition to this renderer type.

@all @nyalldawson : one issue I always had with the point displacement renderer is that you can't pick indiviual features - the identify tool is tied to the central point and then you get all features, not just one individual one you want to pick. Would this be possible to solve in a future QGIS version? Probably not easy ...

2017-03-29 13:00 UTC, gioman commented
> @all @nyalldawson : one issue I always had with the point displacement renderer is that you can't pick indiviual features - the identify tool is tied to the central point and then you get all features, not just one individual one you want to pick. Would this be possible to solve in a future QGIS version? Probably not easy ...

I believe I reported this (ages ago) as bug/improvement on our bug tracker. It would be very convenient indeed to be able identify each feature.

2017-10-26 21:47 UTC, nyalldawson commented
@myarjunar

I've opened a new PR with this work at #5472  - it's your commits + some unit tests, so that we can get this merged before 3.0 freeze.

2017-10-26 21:47 UTC, closed without merging