[server][wmts][fix] updated constant to correct resolution in WMTS tile grid initialization
qgis/QGIS pull request #43418
Opened 2021-05-27 07:39 UTC by andreassteffens

Constant needed to be updated in order to match the standard rendering pixel size of 0.28mm x 0.28mm defined by the OGC resulting in DPI of 90.71428571429.

Should fix #34826, #42942, #39040

2021-05-27 11:57 UTC, elpaso commented on src/server/services/wmts/qgswmtsutils.cpp
> +    double POINTS_TO_M = 2.800005600011068 / 10000.0;
```suggestion
    const double POINTS_TO_M = 2.800005600011068 / 10000.0;
```

2021-05-27 13:45 UTC, rldhont requested changes
thanks @andreassteffens can you also const tileSize ?

2021-05-27 14:46 UTC, DelazJ commented
> Should fix #34826, #42942, #39040

@andreassteffens if you want the three to be closed, the "fix" mention should be added for all, ie `Should fix #34826, fix #42942, fix #39040`

2021-05-28 07:13 UTC, rldhont approved these changes

2021-05-31 08:24 UTC, rldhont commented
@andreassteffens can you run the tests and update the WMTS GetCapabilities that failed.

2021-05-31 10:33 UTC, andreassteffens commented
will take a look at the test case ASAP

2021-06-08 22:10 UTC, merged