New geometry class: QgsRegularPolygon
qgis/QGIS pull request #4502
Opened 2017-05-04 15:40 UTC by lbartoletti

Here the last geometry taken from CAD plugins.
I have change the operator== for QgsTriangle to have a "better" method.

I will have to add the support for the inclination for this class and others.

2017-05-04 18:55 UTC, lbartoletti commented
No error, but "Build and test timeout. Please restart the build for meaningful results." for xcode8.3

2017-05-04 19:47 UTC, m-kuhn commented
I've restarted the job on travis. In case this happens again, you can always rebase and force push or close and reopen the pull request to restart a job.

2017-05-04 22:37 UTC, nyalldawson requested changes
Looking great (as usual), but some changes required.

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> + * \brief Regular Polygon geometry type.
Can you add a bit more detail here? Something like the wikipedia definition: "A regular polygon is a polygon that is equiangular (all angles are equal in measure) and equilateral (all sides have the same length). Regular polygons may be convex or star and include shapes like hexagons and pentagons."

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> + * A regular polygon is defined by a center point with a number of sides/vertices, a radius and the first vertice.
vertice -> vertex

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    /** Constructs a regular polygon by center and parameters for the first vertice. An empty regular polygon is returned if numSides < 3 or circle option isn't valid.
if \a numSides < 3

the \a annotation will cause numSides to be formatted as an argument in the doxygen pages

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +     * \param radius Distance from the center and the first vertice or sides (see \a circle).
vertice->vertex (also many other occurances)

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    QgsRegularPolygon( const QgsPointV2 center, const double radius, const double azimuth, const int numSides, const int circle );
Should be QgsPointV2&

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +enum ConstructionOption
Can you move this inside the QgsRegularPolygon class, and rename the options to InscribedCircle and CircumscribedCircle to keep with the standard formatting.

Also needs some docs for these options/enum.

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    QgsRegularPolygon( const QgsPointV2 center, const double radius, const double azimuth, const int numSides, const int circle );
Use ConstructionOption instead of int for circle

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    /** Constructs a regular polygon by center and another point.
\a center

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    QgsRegularPolygon( const QgsPointV2 center, const QgsPointV2 pt1, const int  numSides, const int circle );
pass center by reference, use ConstructionOption for circle

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    QgsRegularPolygon( const QgsPointV2 pt1, const QgsPointV2 pt2, const int  numSides );
pass QgsPointV2 by reference

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    virtual bool operator ==( const QgsRegularPolygon &rp ) const;
Do we need these virtual methods? As far as I can see this class isn't going to be subclassed, so removing the virtual keyword will optimise the class

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    virtual bool isEmpty() const;
Again - is virtual needed here?

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    QgsPointV2 center() const {return mCenter; }
{return -> { return

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    double apothem() const {return mRadius * cos( M_PI / mNumSides ); }
I really like how thoroughly you design these classes!

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    void setCenter( const QgsPointV2 center );
pass by reference

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    int numSides() const {return mNumSides; }
can you change this to either sides() or numberSides()? We are removing abbreviations from the API in 3.0 to keep things consistent and predictable

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    void setVertice( const QgsPointV2 vertice );
setFirstVertex, pass by reference

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    void setNumSides( const int numSides );
setNumberSides

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    void points( QgsPointSequence &pts SIP_OUT ) const;
Nicer api would be 

    QgsPointSequence points() const;

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +    QgsTriangle toTriangle( ) const;
How does this work? What happens with a 6 sided polygon?

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +     * returns a string representation of the regular polygon.
returns -> Returns

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +  protected:
These should be private

2017-05-04 22:37 UTC, nyalldawson commented on src/core/qgsexpression.cpp
> +                               << Parameter( QStringLiteral( "number of sides/edges" ) )
missed this above, but these names are variable names, so must be unique for the function, and number_of_sides format only. "semi-minor axis" and the other existing ones will need fixing too.

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.cpp
> +    if ( circle == ConstructionOption::inscribedCircle )
use a switch here

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.cpp
> +  mNumSides = 0;
Can you move these initializations to the header? (c++11 style)

2017-05-04 22:37 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.cpp
> +    if ( circle == ConstructionOption::inscribedCircle )
Use switch

2017-05-05 09:24 UTC, lbartoletti commented on src/core/geometry/qgsregularpolygon.h
> +    virtual bool operator ==( const QgsRegularPolygon &rp ) const;
No, unfortunate cut/paste...

2017-05-05 09:29 UTC, lbartoletti commented on src/core/geometry/qgsregularpolygon.h
> + * \brief Regular Polygon geometry type.
OK. Except for star polygon (TODO idea)

2017-05-05 09:33 UTC, lbartoletti commented on src/core/geometry/qgsregularpolygon.h
> +    void points( QgsPointSequence &pts SIP_OUT ) const;
I agree with you. I kept the conventions of the other classes (LineString/Curve).

I will also change in QgsEllipse.

2017-05-05 09:34 UTC, lbartoletti commented on src/core/geometry/qgsregularpolygon.h
> +    QgsTriangle toTriangle( ) const;
I will rewrite the comment by including the empty return if the number of sides is less than 3

2017-05-05 14:01 UTC, lbartoletti commented
Thank you for your advice. I think I have made the necessary changes.

2017-05-09 23:48 UTC, nyalldawson reviewed
Nearly there - just some tiny fixes left!

2017-05-09 23:48 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +      InscribedCircle, //! Inscribed in a circle (the radius is the distance between the center and vertices)
Here //! needs to be //!< , since the doc comes after the declaration

2017-05-09 23:48 UTC, nyalldawson commented on src/core/geometry/qgsregularpolygon.h
> +     * \see setVertice()
\see setFirstVertex()

2017-05-10 11:14 UTC, lbartoletti commented on src/core/geometry/qgsregularpolygon.h
> +     * \see setVertice()
Sorry !
Travis won't build it on Mac but I think it's ok. 

Thanks.

2017-05-10 12:23 UTC, merged

2017-05-10 12:23 UTC, nyalldawson commented
Merged, thanks!