[CFT] Fix topological editing different crs v2
qgis/QGIS pull request #45357
Opened 2021-10-01 14:37 UTC by lbartoletti

## Description

This is a new version of the PR #41306 but without the issues (I hope!) that forced to do a revert.

@nyalldawson @gioman is it possible to try your map tools with this patch?

2021-10-01 14:41 UTC, gioman commented
> @nyalldawson @gioman is it possible to try your map tools with this patch?

@lbartoletti I will try.

2021-10-18 06:58 UTC, lbartoletti commented on src/app/qgsmaptooladdfeature.cpp
> +          }
IIRC it ensures that topological points are inserted from the geometry. Dunno if it was not a request...
Anyway, this PR is for layer with different CRS. The logic remain the same.

2021-10-21 19:31 UTC, uclaros commented on src/app/qgsmaptooladdfeature.cpp
> +          }
Woops! I thought `snappingMatches()` only returned the points that were snapped but since it contains all digitized points it makes sense!

2021-10-21 21:29 UTC, uclaros requested changes

2021-10-21 21:29 UTC, uclaros commented on tests/src/app/maptooladdfeatureline/testqgsmaptooladdfeatureline.cpp
> +  QCOMPARE( mLayerCRS3945Line->getFeature( mFidLine3945 ).geometry().asWkt( 2 ), QgsGeometry::fromWkt( new3945Wkt ).asWkt( 2 ) );
Judging by the coordinates in the comment (2 2, 8 2, 8 4, 8 8) (there is no such linestring in the test), something probably got mixed up here. This doesn't test the PR's proposed functionality. You should test that topological points were added to the 3946 layer when digitizing on the 3945.
The test as it is is already passing in master without the PR!

2021-10-21 21:29 UTC, uclaros commented on tests/src/app/maptooladdfeatureline/testqgsmaptooladdfeatureline.cpp
> +  mLayerCRS3946Line->undoStack()->undo();
This only undoes the topological point, not the line itself.

2021-12-11 02:42 UTC, closed without merging