[Doc] Add folders for documentation generation
qgis/QGIS pull request #46037
Opened 2021-11-15 10:05 UTC by Koyaani

## Description

During the documentation build, I find few issues.

Some Doxygen conditions were missing (.h in private but not .cpp, end condition). I added them when Doxygen raised a warning.

The folder `/src/core/externalstorage` was missing in doc/CMakeLists.txt, maybe others have been forgotten. I know that some folders are almost empty with only private classes. As Doxygen doesn't take them in account, we can add them all to avoid to being forgotten if public classes are added.

So, this PR also adds all the folders and then sorts them alphabetically. I don't know how relevant that is :confused: 

The list of added folders:

`/src/core/editform`
`/src/core/externalstorage`
`/src/core/processing/models`
`/src/core/providers/ept`
`/src/core/providers/meshmemory`
`/src/core/providers/ogr`
`/src/core/settings`
`/src/core/simplify`

`/src/gui/attributeformconfig`
`/src/gui/mesh`
`/src/gui/providers`
`/src/gui/providers/ept`
`/src/gui/providers/gdal`
`/src/gui/providers/ogr`
`/src/gui/settings`
`/src/gui/tableeditor`
`/src/gui/vector`

`/src/3d/processing`
`/src/3d/shaders`
`/src/3d/shaders/mesh`

`/src/server/services/wmts`
`/src/server/services/wfs3`

2021-11-15 15:57 UTC, troopa81 requested changes

2021-11-15 16:00 UTC, troopa81 commented
Thanks for this! Maybe the best way to guess if we should add a folder or not is to check in the core_auto.sip, gui_auto.sip, server_auto.sip files if there is files included from this folder (which is the case of externalstorage or geometry for instance, but not providers)

2021-11-16 12:23 UTC, Koyaani commented on doc/CMakeLists.txt
> +        ${CMAKE_SOURCE_DIR}/src/server/services
But that means we should remove classes of the documentation that are currently present there ? like `QgsWcs::QgsServiceException` (`src/server/services/wcs/qgswcs.cpp`)

2021-11-17 15:52 UTC, troopa81 commented on doc/CMakeLists.txt
> +        ${CMAKE_SOURCE_DIR}/src/server/services
I'd say yes! This class is not part of the API, this is internal code like the app folder. There is now way to use this object in PyQGIS, so it has nothing to do in documentation.

2021-11-18 04:36 UTC, nyalldawson commented on doc/CMakeLists.txt
> +        ${CMAKE_SOURCE_DIR}/src/server/services
Just to clarify -- please don't remove any existing documentation -- even if it's in private/internal code it can still be useful!

2021-11-18 07:55 UTC, troopa81 commented on doc/CMakeLists.txt
> +        ${CMAKE_SOURCE_DIR}/src/server/services
@nyalldawson But what's the rule exactly for documentation ? Only class that are part of the PyQGIS API (but server/services and providers are not part of it) or all classes (but then app folder and other one are missing) ?

2021-11-18 19:37 UTC, nyalldawson commented on doc/CMakeLists.txt
> +        ${CMAKE_SOURCE_DIR}/src/server/services
There's no rule like that -- public API must be documented, but there's no reason to avoid documentation elsewhere (in fact, it's a good thing!)

2021-12-02 08:50 UTC, Koyaani commented on doc/CMakeLists.txt
> +        ${CMAKE_SOURCE_DIR}/src/server/services
As there is no global decision, I prefer not to change the content of the documentation too much. I will add the files that are present in the API but not in the documentation, without removing any.

2021-12-03 08:53 UTC, Koyaani commented on src/gui/providers/qgspointcloudsourceselect.cpp
> +///@cond PRIVATE
I don't think this condition should be removed because it is present in all the other files of this folder and subfolder.

2021-12-13 13:30 UTC, Koyaani commented
The new list of added folders is :
- `src/core/editform`
- `src/core/externalstorage`
- `src/core/processing/models`
- `src/core/settings`
- `src/gui/mesh`
- `src/gui/settings`
- `src/gui/tableeditor`
- `src/gui/vector`
- `src/3d/processing`

2021-12-15 08:11 UTC, troopa81 reviewed
One little comment and I'm good to go! Thanks for this @Koyaani

2021-12-15 08:11 UTC, troopa81 commented on src/gui/mesh/qgsmeshlayerproperties.h
> +     * \param canvas
Could you add a comment for these parameters?

2021-12-16 08:49 UTC, troopa81 approved these changes

2021-12-16 14:09 UTC, merged