Added 'last_value' to aggregate function list
qgis/QGIS pull request #46211
Opened 2021-11-25 12:43 UTC by Gutzeit555

fixes Issue 6623 in the qgis/QGIS-Documentation repository
I made further changes to the list, as it did not seem up to date to me:
added „first_value“
deleted „stdevsample“
renamed „min“ to „minimum“
renamed „max“ to „maximum“

## Description

[Replace this with some text explaining the rationale and details about this pull request]

2021-11-25 14:35 UTC, m-kuhn commented
https://github.com/qgis/QGIS-Documentation/issues/6623
CC  @nirvn

2021-11-25 14:56 UTC, nirvn approved these changes
Nice papercut fix.

2021-11-25 16:50 UTC, DelazJ commented
Unless I miss recent changes, are you sure of these? It doesn't look enough to me. Using max/min/stdevsample in an expression dialog, I can get output while maximum/minimum return invalid expression in the dialog. Same for first_value and last_value. No such aggregates.

@nirvn, any reason there's no direct first_value and last_value functions in the aggregates group?

2021-11-25 18:19 UTC, Gutzeit555 commented
@DelazJ 
This is the list from the drop-down menu for "Aggregate Function" in the dialog I get from „Aggregate“ in the Processing Toolbox (see picture). I tried the functions described and they worked. I assumed that this list is complete and correct and that the same function is also used in the expression dialog, also because the link in section "25.1.16.3. Aggregate" leads there. Is this not correct?
![aggregate](https://user-images.githubusercontent.com/61974701/143487228-79b3a5e0-8461-4a5b-8027-10cb6294579f.png)

2021-11-25 22:16 UTC, nyalldawson commented
> Unless I miss recent changes, are you sure of these? It doesn't look enough to me. Using max/min/stdevsample in an expression dialog, I can get output while maximum/minimum return invalid expression in the dialog. Same for first_value and last_value. No such aggregates.

The change IS incorrect -- it's 100% "min" and "max" (direct from the code, and see eg https://github.com/qgis/QGIS/blob/master/tests/src/core/testqgsexpression.cpp#L2349)

2021-11-25 22:17 UTC, nyalldawson requested changes

2021-11-25 22:17 UTC, nyalldawson commented on resources/function_help/json/aggregate
> +	{"arg":"aggregate", "description":"a string corresponding to the aggregate to calculate. Valid options are:<br /><ul><li>count</li><li>count_distinct</li><li>count_missing</li><li>minimum</li><li>ma
```suggestion
	{"arg":"aggregate", "description":"a string corresponding to the aggregate to calculate. Valid options are:<br /><ul><li>count</li><li>count_distinct</li><li>count_missing</li><li>min</li><li>max</li><li>sum</li><li>mean</li><li>median</li><li>stdev</li><li>range</li><li>minority</li><li>majority</li><li>q1: first quartile</li><li>q3: third quartile</li><li>iqr: inter quartile range</li><li>min_length: minimum string length</li><li>max_length: maximum string length</li><li>concatenate: join strings with a concatenator</li><li>concatenate_unique: join unique strings with a concatenator</li><li>collect: create an aggregated multipart geometry</li><li>array_agg: create an array of aggregated values</li><li>first_value</li><li>last_value</li></ul>"},
```

2021-11-25 22:18 UTC, nyalldawson commented
This PR is incorrect -- none of the changes are valid

2021-11-26 08:40 UTC, Gutzeit555 commented
I'm not sure I understand: are there different functions used in the Processing Toolbox and the expression editor?
btw: I don't know if it's important, but in the [aggregates group](https://docs.qgis.org/testing/en/docs/user_manual/expressions/functions_list.html#id74) it also says minimum and maximum.

2021-11-26 08:57 UTC, DelazJ commented
@Gutzeit555 The link in the [aggregate algorithm docs](https://docs.qgis.org/3.22/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#aggregate) points to the [aggregates group](https://docs.qgis.org/3.22/en/docs/user_manual/expressions/functions_list.html#aggregates-functions) (which the drop-down list in the alg derives from) and not the [aggregate function](https://docs.qgis.org/3.22/en/docs/user_manual/expressions/functions_list.html#aggregate) that this PR is modifying.
The issue with qgis/QGIS-Documentation#6623 is that there's no "first value" and "last value" function in the aggregates group functions. They exist nowhere but in that algorithm, and we don't want to document (if needed) them there. Reason why I was asking whether there's a reason they do not exist as expression function (_replying to myself, maybe because of array_first and array_last?_) .

2021-11-26 08:59 UTC, DelazJ commented
The other issue I see your PR raise is why the aggregate function doesn't have minimum and maximum as aggregate parameter (all the other parameters name matches an existing aggregate function) instead of min and max.

2021-11-26 09:42 UTC, Gutzeit555 commented
Ok, I understood my mistake, everything is wrong. I'm really sorry about the confusion!
What can I do to cancel this PR?

2021-11-26 10:20 UTC, m-kuhn commented
Let's close this. A new issue has been opened for aliases.
@Gutzeit555 If you have more ideas to for fixes, please open a PR again any time.

2021-11-26 10:20 UTC, closed without merging

2021-11-26 10:37 UTC, DelazJ commented
> Ok, I understood my mistake, everything is wrong. I'm really sorry about the confusion!

No worries. I can't count the number of "wrong" PRs I've opened :smile:. The mismatch of parameters is confusing and you help find an inconsistency in the function, anyway.
And as @m-kuhn said, do not hesitate to open new PR if you want to fix anything else.

2021-11-26 15:20 UTC, Gutzeit555 commented
Thank you!  I will keep trying ;-)