disable camera movement when the clicked position is void
qgis/QGIS pull request #46890
Opened 2022-01-19 11:21 UTC by NEDJIMAbelgacem

## Description
When the clicked area has nothing rendered (a void area), the camera behaves weirdly as it picks a very far point as a zoom or rotation center. This PR disables the camera movement when that picked point is void.

2022-01-19 21:16 UTC, nyalldawson commented
How does this work if you only have a single point cloud layer loaded? Does it mean you have to click right on a point to navigate?

2022-01-20 12:28 UTC, uclaros commented
Nyall's concern is valid also for cases where the background if the pointcloud is void, like a front view.
My suggestion would be to implement the following logic:
- if depth is 1, query the depth buffer's neighboring 8 pixels and use the minimum value.
- if still 1, go for 15 or 24 (4x4 or 5x5 neighbours).
- if still 1, it means the user has probably clicked straight into the void. In that case instead of ignoring his input, calculate the average value of the whole depth buffer and use this to get the center of rotation.

2022-01-24 13:29 UTC, NEDJIMAbelgacem commented
Thank you for the feedback @uclaros & @nyalldawson
I changed the behaviour to be like this:
- Query the 9 by 9 square around the clikced pixel for depth
- If the depth is 1 (meaning we are in a non rendered area), we calculate the average of the rendered pixels (depths that are different than 1)

2022-01-24 16:15 UTC, uclaros requested changes
In general this gives great usability! My only concern is with the right mouse zooming, where zooming to void was not troublesome..

2022-01-24 16:15 UTC, uclaros commented on src/3d/qgscameracontroller.cpp
> +#include <QElapsedTimer>
```suggestion
```

2022-01-25 10:56 UTC, NEDJIMAbelgacem commented on src/3d/qgscameracontroller.cpp
> +      }
The Panning and rotating are totally unrealted to the right button zooming.
I think this allows for more uniform behaviour accross navigation controls and this change still allows precise zooming with the right button. In any case you wouldn't want to zoom towards a very far point anyway...

2022-01-25 10:56 UTC, NEDJIMAbelgacem commented on src/3d/qgscameracontroller.cpp
> +      double d = ( ( qRed( pixel ) / 255.0 + qGreen( pixel ) ) / 255.0 + qBlue( pixel ) ) / 255.0;
This is faster by around 50% in debug :)

2022-01-25 16:22 UTC, uclaros requested changes
Minor stuff again.

2022-01-25 16:22 UTC, uclaros commented on src/3d/qgscameracontroller.h
> +    // Returns the minimum depth value in the square [px - 3, px + 3] * [py - 3, py + 3]
```suggestion
    /**
     * Returns the minimum depth value in the square [px - 3, px + 3] * [py - 3, py + 3]
     * If the value is 1, the average depth of all non void pixels is returned instead.
     */
```

2022-01-25 16:22 UTC, uclaros commented on src/3d/qgscameracontroller.cpp
> +      double d = ( ( qRed( pixel ) / 255.0 + qGreen( pixel ) ) / 255.0 + qBlue( pixel ) ) / 255.0;
I would prefer if you always used the same function for depth decoding, so maybe change `Qgs3DUtils::decodeDepth` to use `pixel()` instead.

2022-01-26 10:44 UTC, uclaros approved these changes
Yay! \o/

2022-01-26 13:05 UTC, merged