Fix the mandatory OnlineResource
qgis/QGIS pull request #4700
Opened 2017-06-08 13:25 UTC by sbrunner

I not sure that well understand the expected result, I see that:

* in the WMS specification the OnlineResource is required in the Service tag.
* in the Service tag we get the OnlineResource from the project configuration.
* in the other tag we automatically generate the OnlineResource from the request.

What should we finally do?

2017-06-08 13:53 UTC, elpaso commented
@sbrunner the expected behavior is:
- if the onlineresource is specfied in the OWS project settings, use that one
- if it is not specified, get it from request

2017-06-08 14:07 UTC, sbrunner commented
@elpaso make sense, then I will do ti for all the OnlineResource?

2017-06-08 16:16 UTC, rldhont requested changes
@sbrunner the OnlineResource in the Service Tag is not for the Web Service. It's a link for resources about the Web Service.
In the documentation, the OnlineResource in the Service Tag is defined as 
> Top-level web address of service or service provider
In teh QGIS project there is 4 possible OnelineResource:
* 1 for Service description
* 1 for WMS service
* 1 for WFS service
* 1 for WCS service

2017-06-09 06:17 UTC, sbrunner commented
@rldhont in a QGIS server all of them is the same addresses (as for mapserver)... And the "Service description" is as I know not an ogc service ...

2017-06-09 08:15 UTC, rldhont commented
@sbrunner All the OnlineResource can be different not only because you can defined the forth in QGIS but because some users don't want to use the same address for the different services.

The OnlineResource in the Service Tag is defined for WMS as the _Top-level web address of service or service provider_ and it is stored in the project as* WMSOnlineResource*.

The OnlineResource for WMS service used for request is stored in the project as *WMSUrl*, if it is not defined get the URL from the request.

The OnlineResource for WFS service used for request is stored in the project as *WFSUrl*, if it is not defined get the URL from the request.

The OnlineResource for WCS service used for request is stored in the project as *WCSUrl*, if it is not defined get the URL from the request.

I don't know if all of these rules has been used well implemented.

2017-06-09 08:45 UTC, rldhont requested changes

2017-06-09 08:45 UTC, rldhont commented on src/server/services/wms/qgswmsgetcapabilities.cpp
> +    onlineResourceElem.setAttribute( QStringLiteral( "xlink:href" ), serviceUrl( request, project ) );
This line has to be updated:
```
onlineResourceElem.setAttribute( QStringLiteral( "xlink:href" ), onlineResource );
```

2017-06-09 08:45 UTC, sbrunner commented
@rldhont thanks for your response, I get a better understanding, but what should be do if the WMSOnlineResource config isn't fill?
May last solution isn't good? Should I change something?

2017-06-09 08:54 UTC, sbrunner commented on src/server/services/wms/qgswmsgetcapabilities.cpp
> +    onlineResourceElem.setAttribute( QStringLiteral( "xlink:href" ), serviceUrl( request, project ) );
thanks :-)

2017-06-09 08:54 UTC, rldhont commented on src/server/services/wms/qgswmsgetcapabilities.cpp
> +    onlineResourceElem.setAttribute( QStringLiteral( "xlink:href" ), serviceUrl( request, project ) );
You calculated onlineResource and does not use it in the element.

2017-06-09 11:48 UTC, sbrunner commented
@rldhont Corrected and tests pass :-)

2017-06-09 11:51 UTC, rldhont approved these changes

2017-06-09 11:52 UTC, merged

2017-06-09 11:52 UTC, rldhont commented
Thanks @sbrunner 
Will you check WMSUrl ?

2017-06-09 11:54 UTC, sbrunner commented
It's checked in `serviceUrl` :-)

2017-06-09 12:04 UTC, rldhont commented
Thanks, I will check for WFS and WCS.