#16706, categorized symbology matching lack of value is not properly encoded in SLD
qgis/QGIS pull request #4725
Opened 2017-06-13 12:37 UTC by aaime

Having a rule based symbology like:

````
      <renderer-v2 attr="dcpNotAffe" forceraster="0" symbollevels="0" type="categorizedSymbol" enableorderby="0">
        <categories>
          ...
          <category render="true" symbol="2" value="" label="No information"/>
````
results in value = "" being transformed in the following SLD filter:

````
<ogc:PropertyIsEqualTo>
  <ogc:PropertyName>dcpNotAffe</ogc:PropertyName>
  <ogc:Literal></ogc:Literal>
</ogc:PropertyIsEqualTo>
````

However this is not a 1-1 equivalent, as QGIS matches both empty strings and null values, so if the data has nulls, for that category, a SLD based renderer will display nothing in it. The filter should really be:

````
<ogc:Or>
  <ogc:PropertyIsNull>
    <ogc:PropertyName>dcpNotAffe</ogc:PropertyName>
  </ogc:PropertyIsNull>
  <ogc:PropertyIsEqualTo>
    <ogc:PropertyName>dcpNotAffe</ogc:PropertyName>
    <ogc:Literal></ogc:Literal>
  </ogc:PropertyIsEqualTo>
</ogc:Or>
````

2017-06-13 13:22 UTC, aaime commented
Can anyone help me understand the spell checking build error?

````
2: TRAVIS PR BRANCH: sld_categorize_null_empty
2: Running spell check on files: src/core/symbology-ng/qgscategorizedsymbolrenderer.cpp tests/src/python/test_qgssymbollayer_createsld.py tests/testdata/symbol_layer/categorizedEmptyValue.qml 
2: Progress: 0/6
2: Progress: 1/6
2: Progress: 2/6
2: Progress: 3/6
2: Progress: 4/6
2: tests/testdata/symbol_layer/categorizedEmptyValue.qml
2: 10:    <edittype widgetv2type="TextEdit" name="repID">
2: 415:    <alias field="repID" index="2" name=""/>
2: Progress: 5/6
2: some errors have been found.
2/5 Test #2: qgis_spelling ....................***Failed   24.12 sec
Spell check
````

Seems like it's not liking the repID name in the qml file... but what does it mean? The qml file has been generated as an export from a project, and this is a test file, so why subject it to spell checking to start with?

2017-06-13 13:35 UTC, luipir commented
as far as I remember there is a white list of files to avoid to check... please @3nids or @m-kuhn any hint?

2017-06-14 14:08 UTC, aaime commented
I found that "repid" is part of the spelling.dat file, with a correction to "rapid", so changed that one string, hopefully that will fix the build.

2017-06-14 15:19 UTC, aaime commented
Now the build is failing because the SIP file is not up to date... but I did not touch any public method signature so... what gives? Do I need to rebase on the current master?

2017-06-14 17:08 UTC, aaime commented
Nope, looks like master is failing in the same way

2017-07-11 15:37 UTC, aaime commented
@luipir finally passing (just had to rebase a few times until I hit a baseline that was building).

2017-07-11 15:53 UTC, luipir commented
plas plas 
I will give a bunch of review of all SLD related stuffs next week (backport and master fixes)... tomorrow I'll be travelling.

2017-07-11 16:07 UTC, m-kuhn commented
Sounds good to me. I was shortly considering to implement sld behavior in qgis. But give that often ppl won't even notice and those that require more control over NULL vs "" can use rulebased, let's stick to ehat we have 👍

2017-07-18 09:34 UTC, luipir commented
IMHO This could be a good candidate for backport to 2.18.

2017-07-18 09:47 UTC, luipir reviewed
need crarification by @m-kuhn

2017-07-18 09:47 UTC, luipir commented on src/core/symbology-ng/qgscategorizedsymbolrenderer.cpp
> +  if ( mValue.isNull() || mValue.toString().isEmpty() )
@m-kuhn what do you mean with more control on "" and NULL using rule based? with this PR they are managed in the same way. Are you thinking to split the "or" with two different rules?

2017-07-18 10:28 UTC, m-kuhn commented on src/core/symbology-ng/qgscategorizedsymbolrenderer.cpp
> +  if ( mValue.isNull() || mValue.toString().isEmpty() )
Yep, exactly

2017-07-18 12:55 UTC, luipir requested changes
please @aaime can you split management of isNull and isEmpty with two different rules and adapt the related tests?

2017-07-21 14:38 UTC, aaime commented
Hi @luipir I'll try to have a look when I come back home next week.

2018-05-28 02:33 UTC, nyalldawson commented
@m-kuhn I looked into your requested changes, but I don't think they are required -- the categorized renderer itself doesn't have any concept of NULL, and always replaces NULL values with empty strings internally.  So I've rebased against master in #7092 and will merge and close this long-overdue PR :)

2018-05-28 02:33 UTC, closed without merging