[needs-docs] raster metadata viewer
qgis/QGIS pull request #4726
Opened 2017-06-13 13:03 UTC by Gustry

## Description

This PR brings the same user experience as in the vector layer properties dialog.

Before : 
* Some read only fields in the General tab and Metadata tab.
![screen shot 2017-04-14 at 15 04 04](https://cloud.githubusercontent.com/assets/1609292/25043904/aaa486a2-2123-11e7-95d3-7d851be0d15d.png)

After:
Some new tabs, like in the vector layer dialog now.
* New information tab
![screen shot 2017-04-14 at 15 09 30](https://cloud.githubusercontent.com/assets/1609292/25044112/f4ee9486-2124-11e7-8978-1c3b003dedf7.png)

* Metadata tab
![screen shot 2017-04-14 at 15 13 17](https://cloud.githubusercontent.com/assets/1609292/25044116/feac7344-2124-11e7-9624-ec9058c0a960.png)

* New source tab
![screen shot 2017-04-14 at 15 12 51](https://cloud.githubusercontent.com/assets/1609292/25044094/e062f23c-2124-11e7-9d59-7614ae64f7c3.png)

* New rendering tab
![screen shot 2017-04-14 at 15 12 26](https://cloud.githubusercontent.com/assets/1609292/25044080/d1e56050-2124-11e7-90c9-fb6803eb7d4a.png)

I would like to merge this first if possible and improve the HTML output in a separate PR later. There is already a HTML output in the PR, but I can add more informations later again. I would like to work on the metadata wizard editor.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

Funded by World Bank
CC : @timlinux

2017-06-13 14:16 UTC, nirvn commented
@Gustry , any chance you could fix the icon size for the metadata panel symbol? It doesn't align with other icons there and thus looks less-than-ideal. That's especially true if you fully collapse the area to only show icons.

2017-06-14 07:11 UTC, timlinux commented
LGTM

2017-06-19 06:22 UTC, Gustry commented
@nirvn Yes sure, but it's a PNG, so I need to find a similar SVG I guess. Any hint where we take SVG for QGIS?

2017-06-19 07:06 UTC, nirvn requested changes
@Gustry , I've vectorized the icon in commit cef089a , hope that can be of help to you.

Spotted one small tooltip change required.

2017-06-19 07:06 UTC, nirvn commented on src/ui/qgsrasterlayerpropertiesbase.ui
>             <string>General</string>
I'm pretty sure you want to update the toolTip string to Metadata.

2017-06-19 07:06 UTC, nirvn commented on src/ui/qgsrasterlayerpropertiesbase.ui
> +            <normaloff>:/images/themes/default/console/iconShowEditorConsole.png</normaloff>:/images/themes/default/console/iconShowEditorConsole.png</iconset>
As of commit cef089a , you have a nice vector (and properly sized) image you should use instead of this PNG.

2017-06-19 07:10 UTC, nirvn commented
BTW, I'm kind of -0 in adding a source tab/panel with a single widget in it. 

Would it be possible to merge the pyramid stuff into the source panel? That's just a suggestion here, but would love to hear what others have to say about this.

2017-06-19 07:41 UTC, Gustry commented on src/ui/qgsrasterlayerpropertiesbase.ui
>             <string>General</string>
Fixed

2017-06-19 07:42 UTC, Gustry commented on src/ui/qgsrasterlayerpropertiesbase.ui
> +            <normaloff>:/images/themes/default/console/iconShowEditorConsole.png</normaloff>:/images/themes/default/console/iconShowEditorConsole.png</iconset>
Thanks a lot, it's much better now!

2017-06-19 07:44 UTC, Gustry commented
I agree I don't really like having only one widget in the source tab, but at least we have the same pattern with the vector layer properties. I happy to update if needed.

2017-06-19 07:45 UTC, nirvn approved these changes

2017-06-19 07:47 UTC, nirvn commented
@Gustry , yeah, I get why you went down that road. I don't have any brilliant alternatives in mind. If nobody comes with better alternative(s), then I guess we should go ahead with this.

@timlinux , @nyalldawson , @NathanW2 , others 😄 , ping for opinion.

2017-06-21 07:37 UTC, timlinux commented
@nirvn I agree it is not great to have a lonely widget in that tab but I also don't have a better solution at this time. If nothing else we should remove the frame from around the CRS picker.

2017-06-23 14:49 UTC, Gustry commented
I removed the frame around the CRS picker : 
![screen shot 2017-06-23 at 16 48 41](https://user-images.githubusercontent.com/1609292/27487391-ead1c4f0-5833-11e7-97bc-48b1556b8bb1.png)

Can-I have some feedback? Thanks

2017-06-24 20:04 UTC, merged

2017-06-24 20:05 UTC, timlinux commented
Thanks @Gustry I went ahead and merged.