Rotate geometry before calculating bounding box in atlas
qgis/QGIS pull request #4730
Opened 2017-06-14 07:47 UTC by Zverik

When maps in the composer were rotated based on current atlas object, the bounding box for the object was calculated without taking the rotation into account. This should fix bugs [11954](https://issues.qgis.org/issues/11954), [8466](https://issues.qgis.org/issues/8466) and [8125](https://issues.qgis.org/issues/8125).

2017-06-14 23:03 UTC, nyalldawson commented
Nice fix for an annoying issue - thanks! Could you add a unit test for this in https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsatlascomposition.py ? 

(by the way, #8466 and #8125 are totally different issues (not related to map rotation). They both relate to rotating any composer item, selecting multiple items, and then attempting to resize using the mouse drag handles)

2017-06-14 23:03 UTC, nyalldawson approved these changes

2017-06-14 23:07 UTC, nyalldawson commented on src/core/composer/qgsatlascomposition.cpp
> +    g.rotate( map->mapRotation(), g.centroid().asPoint() );
Is using the centroid of the geometry correct? I'm thinking possibly this should be the center of the geometry's original bounding box instead.

2017-06-14 23:08 UTC, nyalldawson requested changes
needs clarification regarding use of centroid

2017-06-18 08:09 UTC, Zverik commented
I could not solve the issue of shifted map extend, so for now I grow the extent a little, so the feature is completely inside bounds. Experiments show that the margin is still very small, although for complex features it is noticeable. The math turned out too complex for me, sorry.

The python test is also done. Please take another look at this, @nyalldawson.

2017-06-27 11:51 UTC, 3nids commented
I might not be the right guy for this one. 
@nyalldawson ok for you to merge? or someone else?

2017-06-27 12:02 UTC, nyalldawson commented
Sorry for the delay - I'll take a look again tomorrow

2017-07-03 08:34 UTC, Zverik commented
@nyalldawson ping :)

2017-07-04 19:04 UTC, merged

2017-07-04 19:04 UTC, nyalldawson commented
Nice work - thank you!