Fix estimated featureCount on Oracle views
qgis/QGIS pull request #48515
Opened 2022-05-11 12:24 UTC by Djedouas

## Description

With Oracle provider, the esimated feature count is not working for views.

This PR implements a way to detect if the estimation must be performed on a view or a table and adapts the sql requests accordingly.

It also handles the presence of a filter (where clause of layer subset string).

2022-05-11 15:43 UTC, troopa81 requested changes
Looks good! just 2 minor changes

2022-05-11 15:43 UTC, troopa81 commented on src/providers/oracle/qgsoracleprovider.cpp
> +      QDomNodeList nList = plan.elementsByTagName( "card" );
```suggestion
      const QDomNodeList nList = plan.elementsByTagName( "card" );
```

2022-05-11 15:43 UTC, troopa81 commented on src/providers/oracle/qgsoracleprovider.cpp
> +    QString sql = QStringLiteral( "SELECT object_type FROM all_objects WHERE object_name=? and owner=?" );
```suggestion
    const QString sql = QStringLiteral( "SELECT object_type FROM all_objects WHERE object_name=? and owner=?" );
```

2022-05-12 08:59 UTC, lbartoletti approved these changes

2022-05-13 11:09 UTC, troopa81 commented
@Djedouas you set the 2 comments as resolved but I dont ses any modifications in the code, why?

2022-05-13 12:15 UTC, troopa81 approved these changes

2022-05-23 22:35 UTC, merged