WFS performing binary spatial operations in expressions on server
qgis/QGIS pull request #49372
Opened 2022-07-15 11:27 UTC by signedav

QGIS used to be able to perform the expression filters of binary spatial operations on the server when the geometry was provided as WKT or in the GML format. With this change it converts the geometry when being a static variable in the expression to an OGC filter. The WFS URL is then created combining bbox rectangle, layer-filter and the filtering expression.

A feature request computes the expression in advance to find out, if it can be performed on the server. Then it's stored in `QgsBackgroundCachedSharedData` where a new download is triggered.

When a filter requests is not a pure binary spatial operation, it will not be evaluated on server. This could be future-improved using partial evaluation on server and passing the untranslated part back.

**Open things:**
- [ ] Tests not running properly
- [ ] On having such aggregate operations in expressions for field calculation or symbolization this implementation leads to a lot of downloads (per each feature, since everyone of them has an expression) what can lead to long waiting time (pseudo freeze). Same Situation on other providers. Do we need to consider it?
- [ ] Do we need to consider that GET Requests are too long https://github.com/qgis/QGIS/issues/32348 This is not new since we where able to pass WKT geometries.

2022-07-18 09:55 UTC, rouault requested changes

2022-07-18 09:55 UTC, rouault commented on src/core/qgsogcutils.cpp
> +      otherGeomElem = QgsOgcUtils::geometryToGML( geom, mDoc, mGMLVersion, mSrsName, mInvertAxisOrientation,
otherGeomElem should probably be tested to check it is not the empty QDomElement() returned when the geometry cannot be converted to GML

2022-07-18 09:55 UTC, rouault commented on src/providers/wfs/qgswfsshareddata.cpp
> +  }
those lines, copied&pasted from QgsWFSSharedData::computeFilter(), could be moved in a small helper function

2022-07-18 09:55 UTC, rouault commented on src/providers/wfs/qgswfsfeatureiterator.cpp
> +  qDebug() << "\n\n" << "WFS GetFeature URL: " << getFeatureUrl.toDisplayString() << "\n\n";
This should be removed as redundant with the above QgsDebugMsgLevel()

2022-07-18 09:59 UTC, rouault commented
fix for new failed test in https://github.com/signedav/QGIS/pull/18

2022-07-20 20:39 UTC, rouault approved these changes

2022-07-20 20:46 UTC, merged

2022-07-21 10:40 UTC, signedav commented
Thanks @rouault and @nyalldawson

2023-11-29 15:42 UTC, paul-dorsetcouncil commented
@signedav do you know if anyone ever looked into your comment about GET requests being too long? 

We have been finding that a WFS layer is difficult or even impossible to filter for more than about 3 or 4 features because the filter string is making the URL too long. 

I'd like to find out if others are wanting the change and thought you might know if there is much interest?

2025-01-10 08:33 UTC, kannes commented
@paul-dorsetcouncil please file that as a bug or feature request. Down here in a merged pull request no one would see it unless by accident (hi!).

2025-01-10 08:43 UTC, signedav commented
Thanks @kannes 

@paul-dorsetcouncil I guess you can put your inputs here https://github.com/qgis/QGIS/issues/32348 And btw I haven't worked on this issue since.

2025-01-10 08:44 UTC, kannes commented
Thanks right back at you, @signedav

It looks like @paul-dorsetcouncil already posted there, so this comment thread here can happily go back to sleep. :)