Remove what's this button
qgis/QGIS pull request #4940
Opened 2017-07-28 14:53 UTC by m-kuhn

This removes the "what's this" menu entry in the About menu.

I just tried it on a couple of items (toolbar buttons etc) and I didn't manage to actually hit anything with information.
Tooltips are a much better (less clicks) way to provide hints about what UI elements are here for.

2017-07-28 15:07 UTC, NathanW2 commented
+1 to remove

2017-07-28 19:09 UTC, DelazJ commented
+1 from me too. It'd fix https://github.com/qgis/qgis3_UIX_discussion/issues/34

2017-07-28 21:02 UTC, nyalldawson commented
Very much in favour of killing this. I think there's more needed though - don't most dialogs still include it (on windows)? E.g. https://underdark.files.wordpress.com/2011/10/expression_labeling1.png

We need to remove WindowContextHelpButtonHint flag from all dialogs to do this.

2017-07-29 18:40 UTC, SrNetoChan commented
+1

2017-07-30 03:54 UTC, nirvn commented
+1

2017-07-30 13:25 UTC, m-kuhn commented
> We need to remove WindowContextHelpButtonHint flag from all dialogs to do this.

Do you have an idea how to do this?
It looks to me like it needs to be specified manually everywhere, the most generic approach I can think of is using QgsDialog more extensively.

2017-07-30 19:33 UTC, nyalldawson commented
I'm not sure how widely used QgsGuiUtils:::ModalDialogFlags is used now, but perhaps resurrecting that could be an approach.

2017-08-02 16:09 UTC, m-kuhn commented
We should just bring this upstream. Something like:

    static QDialog::setDefaultWindowHints ()

It's crappy, but the current Qt defaults are rather surprising.

2017-08-03 11:58 UTC, nyalldawson requested changes
I'll volunteer for fixing all the windows title bar buttons. Thanks for this amazing pull reuqest!

2017-08-03 11:59 UTC, merged

2017-08-03 12:00 UTC, m-kuhn commented
Thanks @nyalldawson , a generous and sensible proposal indeed!