always set a default name in the qgis project to avoid discrepancies with GetCapabilities
qgis/QGIS pull request #4958
Opened 2017-08-04 16:14 UTC by Gustry

## Description

always set a default name in the qgis project to avoid discrepancies with GetCapabilities

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

2017-08-04 16:20 UTC, rldhont approved these changes
Thanks!

2017-08-05 14:11 UTC, Gustry commented
Ok, Travis is happy now. Review are welcome. Thanks @rldhont

2017-08-07 16:06 UTC, rldhont commented
@pblottiere @sbrunner can you give you opinion ?

2017-08-08 07:26 UTC, pblottiere commented
Nice work @Gustry! 

 It is just a thought, but do you think it could be possible to set the current style of `QgsMapLayerStyleManager` to the default one without explicitly passing the "default" string in parameter? (which is by the way a translated string)

2017-08-12 08:48 UTC, m-kuhn requested changes
I'm somehow undecided on the use of localized strings that are saved to the project file, translation should be considered representation not data. Although I don't expect issues in the case here. Just to keep in mind ☺

2017-08-12 08:48 UTC, m-kuhn commented on src/core/qgsmaplayerstylemanager.h
> +    QString mEmptyStyleName = tr( "default" );
I think this should go to a private method instead.

2017-08-14 09:26 UTC, Gustry commented on src/core/qgsmaplayerstylemanager.h
> +    QString mEmptyStyleName = tr( "default" );
Done

2017-08-14 09:28 UTC, Gustry commented
I understand about the translated string, but users can already set their own style name if they rename it. Should we remove the use of the `tr` function?

2017-08-14 09:29 UTC, m-kuhn commented on src/core/qgsmaplayerstylemanager.h
> +    QString mEmptyStyleName = tr( "default" );
Can you adjust the name without a `m`-prefix?

2017-08-14 09:30 UTC, Gustry commented on src/core/qgsmaplayerstylemanager.h
> +    QString mEmptyStyleName = tr( "default" );
I did that, the name of the function is `mDefaultStyleName`, not good?

2017-08-14 09:31 UTC, Gustry commented on src/core/qgsmaplayerstylemanager.h
> +    QString mEmptyStyleName = tr( "default" );
SOrry, I read too quick ;-)
I thought that every private members/methods should have a `m` prefix. I will fix that

2017-08-14 09:31 UTC, m-kuhn commented
I'm not completely sure here, just wondering what we will do if we go for https://github.com/qgis/QGIS-Enhancement-Proposals/issues/90 or a multilingual server. However, it's no blocker for me, since the user can adjust it manually.

2017-08-14 09:32 UTC, m-kuhn commented on src/core/qgsmaplayerstylemanager.h
> +    QString mEmptyStyleName = tr( "default" );
Just in case -> `Ctrl + Shift + R` will rename it quickly for you ;)

2017-08-14 09:36 UTC, Gustry commented on src/core/qgsmaplayerstylemanager.h
> +    QString mEmptyStyleName = tr( "default" );
Fixed with `cmd + shift + R` ;-)

2017-08-14 09:38 UTC, m-kuhn commented on tests/src/core/testqgsmaplayerstylemanager.cpp
> +  QCOMPARE( mgr->style( QString( "default" ) ).isValid(), true );
That should be a `QStringLiteral`

2017-08-14 09:39 UTC, m-kuhn commented on src/core/qgsmaplayerstylemanager.h
> +    QString defaultStyleName();
This method should be `const`

2017-08-16 13:45 UTC, rldhont commented
@m-kuhn, are the changes good for you ?

2017-08-16 16:39 UTC, merged

2017-08-16 16:39 UTC, m-kuhn commented
Yes, good job