From Clipboard Cut&Paste fix when attached special field values. Fixies #16870
qgis/QGIS pull request #5030
Opened 2017-08-16 10:53 UTC by luipir

## Description
backport cherry-pick for https://github.com/qgis/QGIS/pull/4980/commits/a2c18104362e16e3cac17829b18d13fd64e1f472
resume:
In some cases when features are attached from clipboard as \t separated string, the import failed due the fact that the fromWkt geometry contructor is build on WKT * dumped fields. In some case when some dumped field has values inside parenthesis "(some value") the fromWkt parser return a ZM geometry.
This patch strips the leading field values leaving only WKT to the parser.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

2017-08-16 10:56 UTC, luipir commented
@nyalldawson @elpaso I did a backport of https://github.com/qgis/QGIS/commit/a2c18104362e16e3cac17829b18d13fd64e1f472
becasue it affect also 2.18 especially when cut&paste is directly from clipboard filled from external text files and not from internal vectorlayer cut&paste.

2017-08-16 16:21 UTC, m-kuhn commented
can you adjust the typo in the commit title so it gets linked to the issue?

2017-08-16 16:24 UTC, m-kuhn requested changes

2017-08-16 16:24 UTC, m-kuhn commented on src/app/qgsclipboard.cpp
> +    feature.setGeometry( *geometry );
I think this leaks the geometry.

2017-08-17 08:36 UTC, luipir reviewed
fixed with https://github.com/qgis/QGIS/pull/5030/commits/b73b25d49594ad84c9bfe86b844344e1af54726f

2017-08-17 08:36 UTC, luipir commented on src/app/qgsclipboard.cpp
> +    feature.setGeometry( *geometry );
fixed... tanks to point out. I read the api too quickly.

2017-08-17 11:04 UTC, m-kuhn approved these changes

2017-08-17 11:07 UTC, luipir commented
@m-kuhn travis fail on qgis3 but succes on qgis 2.x

2017-08-17 11:13 UTC, luipir commented
tnx

2017-08-17 14:39 UTC, merged