[3D] prevent recreating an entity too many times on a renderer change
qgis/QGIS pull request #51965
Opened 2023-02-21 20:45 UTC by ptitjano

## Description

### issue 

While looking at `Qgs3DMapScene::onLayerRenderer3DChanged()`, I realized that this function was called multiple times when updating a 3D renderer via the layer properties panel. This function can be triggered by the `layerModified`, `renderer3DChanged`  or `request3DUpdate` signals. 

It turns out that this these signals can be emitted by 3 different widgets in a Layer properties : 
- `Elevation` which calls `QgsMapLayer::trigger3DUpdate()` and then emits `QgsMapLayer::request3DUpdate` signal
- `the 3D rendered widget` with the `QgsMapLayer::setRenderer3D()` which calls `QgsMapLayer::trigger3DUpdate()` and emits `renderer3DChanged` 
- the fields widget for a vector layer (which is kinda weird) because `QgsVectorLayer::setFieldAlias()` emits `layerModified`

### solutions

Theses issues are solved with the following changes:

For the `elevation` widgets:  apply the logic already used in `QgsPointCloudElevationPropertiesWidget` which is to only call `QgsMapLayer::trigger3DUpdate()` if a relevant 3D property has changed

For the  `fields` widget: check if the alias has really changed. 
As a side note: I'm not sure this really makes sense to trigger a `layerModified` signal for an alias change. There is a TODO note: `// TODO[MD]: should have a different signal?` ;-)

`3D renderer` widget: no change

### limitations and questions

#### `3D renderer` widget

With the current logic, `QgsMapLayer::request3DUpdate` signal is emitted when clicking on the `apply` button even if there isn't any change. I have two ideas to solve this issue but I don't like any of them

1. use the same logic as elevation: check if any property has changed. There can be a lot of properties!
2. compare the previous renderer with the new one. This is already done in `QgsMapLayer::setRenderer3D` but it cannot work because there isn't any appropriate comparison operator on the renderer. The only solution I found would be to write `operator==` for the different renderers and then using dynamic cast in `setRenderer`. It really does not seem like a good idea...

### Is there a difference between `renderer3DChanged` and `request3DUpdate` signals ?

The `request3DUpdate` signal is emitted by `QgsMapLayer::trigger3DUpdate()`
The `renderer3DChanged` signal by `QgsMapLayer::setRenderer3D()`. But `setRenderer3D()` also calls `trigger3DUpdate()` which means that `setRenderer3D()` emits two signals: `renderer3DChanged` and `request3DUpdate`.

These different signals are consumed by `Qgs3DMapScene`. All the layers listen to `request3DUpdate` and only a pointcloud layer also listens to `renderer3DChanged` which is useless because it already listens to `request3DUpdate`

I don't have any pointcloud data to test it but I think one should need to:
- remove the connect(`renderer3DChanged` ) logic of a pointcloud in `Qgs3DMapScene`
- deprecate  `renderer3DChanged` signal because its logic is already covered by  `request3DUpdate`

@benoitdm-oslandia @wonder-sk any thougths ?

2023-02-23 07:10 UTC, benoitdm-oslandia commented
nice one :)

2023-02-24 07:38 UTC, benoitdm-oslandia requested changes
It seems some checks are missing. If not, may be a comment should be added to help in understanding.

2023-02-24 07:38 UTC, benoitdm-oslandia commented on src/app/mesh/qgsmeshelevationpropertieswidget.cpp
> +
Are you missing to check `mStyleComboBox->currentData().toInt()`?

2023-02-24 07:38 UTC, benoitdm-oslandia commented on src/app/raster/qgsrasterelevationpropertieswidget.cpp
> +                                          || props->bandNumber() != mBandComboBox->currentBand();
Are you missing to check mStyleComboBox->currentData().toInt()?

2023-02-24 12:50 UTC, uclaros commented
Regarding the elevation property widgets, should they be calling `QgsMapLayer::trigger3DUpdate()` at all? For point clouds yes, the changes directly affect the 3d representation of data, but for other layer types it seems that they only provide a suggested initial value for a new 3d renderer and not affecting existing ones.

Regarding the 3d rendering widgets, I think I'm ok with them triggering an update on every apply. I you really want to change that, I'd go with adding some `bool QgsAbstract3DRenderer::differencesWarrant3DUpdate( QgsAbstract3DRenderer *other )` method rather than using `operator==` . Also, the comparison in `QgsMapLayer::setRenderer3D` you mention is against the renderer pointer, making sure that it's not the _same_ renderer instance we're talking about. Renderers are expendable, any change to widget parameters will cause the old renderer to be deleted and a new renderer object to be created.

Regarding `renderer3DChanged` and `request3DUpdate` signals, I think the `renderer3DChanged` could indeed be removed. I would extensively test any signal change with real data though, as the pointcloud's _sync 2d renderer with 3d_ functionality might be fragile.
Here's a sample point cloud dataset used in PDAL: https://media.githubusercontent.com/media/PDAL/data/master/autzen/autzen-classified.copc.laz
should also work in qgis as a remote copc file over https

2023-02-27 17:01 UTC, ptitjano commented
Thanks for the feedback and the valuable information!

> Regarding the elevation property widgets, should they be calling `QgsMapLayer::trigger3DUpdate()` at all? For point clouds yes, the changes directly affect the 3d representation of data, but for other layer types it seems that they only provide a suggested initial value for a new 3d renderer and not affecting existing ones.

I honestly don't know. I don't know how these settings affect the 3d rendering. According to git history, this was introduced by @nyalldawson. He might be able to explain why the ``QgsMapLayer::trigger3DUpdate()`  is useful for the other layers.

> 
> Regarding the 3d rendering widgets, I think I'm ok with them triggering an update on every apply. I you really want to change that, I'd go with adding some `bool QgsAbstract3DRenderer::differencesWarrant3DUpdate( QgsAbstract3DRenderer *other )` method rather than using `operator==` . Also, the comparison in `QgsMapLayer::setRenderer3D` you mention is against the renderer pointer, making sure that it's not the _same_ renderer instance we're talking about. Renderers are expendable, any change to widget parameters will cause the old renderer to be deleted and a new renderer object to be created.

Indeed, I don't think this is necessary to check for real changes. I started this change with "why clicking on apply on apply triggers the same signal so many times on each layer?"  and I ended up with a "if we want to go the extra mile, we could also if at least on the parameters has changed".

> 
> Regarding `renderer3DChanged` and `request3DUpdate` signals, I think the `renderer3DChanged` could indeed be removed. I would extensively test any signal change with real data though, as the pointcloud's _sync 2d renderer with 3d_ functionality might be fragile. Here's a sample point cloud dataset used in PDAL: https://media.githubusercontent.com/media/PDAL/data/master/autzen/autzen-classified.copc.laz should also work in qgis as a remote copc file over https

Thank you. I did some testing on pointcloud and with this MR applied, PointCloud rendering still works. However, the pointcloud renderer change logic is still triggered 3 differents times when clicking on apply. This is because both `setrenderers()` and `trigger3DUpdate()` are called in `QgsPointCloudLayer`. The logic move would be to remove `trigger3DUpdate()` because `setrenderers()` already calls `trigger3DUpdate()`. Doing so solves the issue: the logic is only triggered one time, however the rendering is broken: it's all blue :-(
I don't know how pointcloud layers work but I guess this is based on the `pointcloud's _sync 2d renderer with 3d_ ` being broken somewhere. 
I think the simple move at the moment would be to keep this logic. This MR stills reduces from 4 triggers to 3!

I also did some testing of removing `renderer3DChanged`. It still works for all layers.

2023-03-23 20:23 UTC, nyalldawson commented
> Do you know if QgsMapLayer::trigger3DUpdate() is needed for layers which are not point clouds ?

Currently not, but that may change in future

2023-04-14 02:38 UTC, closed without merging