server: make capabilities cache size configurable and add a note when…
qgis/QGIS pull request #52400
Opened 2023-03-27 13:57 UTC by jef-n

2023-03-27 15:49 UTC, elpaso approved these changes
LGTM, see if my comment makes sense.

2023-03-27 15:49 UTC, elpaso commented on src/server/qgscapabilitiescache.cpp
> +  static const int cacheSize = qEnvironmentVariable( "QGIS_SERVER_CAPABILITIES_CACHE_SIZE", "40" ).toInt();
You may want to use toInt( &ok ) and check if ok is true, raise a warning if not.

2023-03-28 07:28 UTC, rldhont commented
@dmarteau can you take a look.

2023-03-29 07:12 UTC, elpaso requested changes
Sorry, having a second thought here: you should use QgsServerSettingsEnv:: API for the server variables.

2023-03-29 11:08 UTC, elpaso approved these changes

2023-03-29 11:08 UTC, elpaso commented on python/server/auto_generated/qgsserversettings.sip.in
> +Returns the QGIS Server capabilities cache size.
Can you specify the uom for the cache size (number of cached capabilities)?

2023-03-29 13:56 UTC, merged