Fix delete curve vertex
qgis/QGIS pull request #53960
Opened 2023-07-26 16:40 UTC by Djedouas

## Description

Fixes a bug when deleting a middle curve vertex.

The deletion was not correctly handled, corrupting the geometry (see picture below, where using the vertex tool we can see a rubber band issue, persisting even after saving the layer), and creating an OGR error when exporting in GPKG (Non contiguous curves).

**Vertex to delete**

![image](https://github.com/qgis/QGIS/assets/34267385/61603f38-9ec8-485b-9847-eeb552978c52)

**After deletion**

![image](https://github.com/qgis/QGIS/assets/34267385/334dd335-4706-405a-8379-57a0bad68618)

## Fix

Test if the vertex to delete is a middle vertex of a curve, and if so, delete the curve and simply replace it with a linestring going from the first to the last vertex and skipping the middle one.

2023-08-11 08:16 UTC, troopa81 requested changes
Does this PR fix also the following deleting issue ?

[errordel.webm](https://github.com/qgis/QGIS/assets/14358135/8553077c-eb43-41fb-91ec-d9ce61bf6eb1)

I didn't test it but looking at the code, I would say no. Am I right?

2023-08-11 08:16 UTC, troopa81 commented on src/core/geometry/qgscompoundcurve.cpp
> +    QgsPoint startPoint = curve->startPoint();
```suggestion
    const QgsPoint startPoint = curve->startPoint();
```

2023-08-11 08:16 UTC, troopa81 commented on src/core/geometry/qgscompoundcurve.cpp
> +    QgsPoint endPoint = nextCurve->endPoint();
```suggestion
    const QgsPoint endPoint = nextCurve->endPoint();
```

2023-08-11 16:05 UTC, Djedouas commented on src/core/geometry/qgscompoundcurve.cpp
> +        if ( subVertexId.vertex < points.length() - 2 )
Yes you're right, I added a commit for this.

2023-08-16 15:24 UTC, troopa81 approved these changes

2023-08-16 15:25 UTC, troopa81 commented
There is still another issue to fix but current behavior is improved with this PR

2023-08-16 15:26 UTC, merged