Implement scoped pointers for gdal handled objects
qgis/QGIS pull request #5423
Opened 2017-10-23 06:22 UTC by nyalldawson

Implements a c++11 unique_ptr with custom deleter for storing/automatic clean up of some gdal object types.

This fixes at least 2 leaks I noticed while implementing this, and I suspect it has the potential to save many more...

2017-10-23 06:25 UTC, m-kuhn commented
Sounds good. What's left to do? I guess sqlite is another candidate.

2017-10-23 06:26 UTC, nyalldawson commented
There's many more gdal objects which could benefit from these. Sqlite would be a great one too - I think we leak a lot with those.

2017-10-23 12:55 UTC, rouault requested changes
LGTM except the 2 cases I outlined

2017-10-23 12:55 UTC, rouault commented on src/providers/ogr/qgsogrprovider.cpp
> +      OGR_F_UnsetField( feature.get(), ogrAttId );
missing .get() in #ifdef OGRNullMarker case

2017-10-23 12:55 UTC, rouault commented on src/providers/ogr/qgsogrprovider.cpp
> +        OGR_F_UnsetField( of.get(), f );
missing .get() in #ifdef OGRNullMarker case

2017-10-23 23:08 UTC, nyalldawson commented
>  What's left to do? I guess sqlite is another candidate.

Another good candidate: the gdal CPL objects. I suspect we leak a lot of those.

2017-10-25 21:38 UTC, nyalldawson commented
@rouault how's d024910 for you?

2017-10-25 21:53 UTC, rouault commented
> @rouault how's d024910 for you?

I've let a few comments.

2017-10-25 21:59 UTC, nyalldawson commented
> I've let a few comments.

Thanks - much appreciated!

2017-10-26 00:02 UTC, merged