qgsmesh3geometry: Limit geometry to 3d scenes' 2d extent
qgis/QGIS pull request #54521
Opened 2023-09-07 16:33 UTC by ptitjano

## Description

From the main commit message: 

```
This is a follow-up of https://github.com/qgis/QGIS/pull/51304 which
did not handle mesh layers. This commit adds this support.

The meshes displayed in a 3d view do not take into account the scene
2d extent.

This issue is fixed by filtering the faces which are used
to build the Qt3D geometry. By using `mesh.faceIndexesForRectangle(
extent )`, it is possible to keep the faces inside `extent`. This list
is then used to populate the `IndexAttribute` of the qt3d
geometry. This way, only the faces inside the extent are displayed.
```

## Current behavior: The whole mesh is displayed

![nocut](https://github.com/qgis/QGIS/assets/497207/1ad397ea-1529-481c-9ffd-3578d238e512)

## New behavior: Only the relevant part of the mesh is displayed

![cut](https://github.com/qgis/QGIS/assets/497207/f728cf55-ae3b-45ff-81ae-29b07a0b6525)

2023-09-07 20:56 UTC, vcloarec requested changes
well done !

2023-09-07 20:56 UTC, vcloarec commented on src/3d/mesh/qgsmesh3dentity_p.cpp
> +  mesh->setGeometry( new QgsMeshDataset3DGeometry( mTriangularMesh, layer(), mMapSettings.temporalRange(), mMapSettings.origin(), mMapSettings.extent(), mSymbol.get(), mesh ) );
`mTriangularMesh` should be in map coordinates

2023-09-07 20:56 UTC, vcloarec commented on src/3d/mesh/qgsmesh3dgeometry_p.cpp
> +  QList<int> facesInExtent = mesh.faceIndexesForRectangle( extent );
`const` ?

2023-09-07 20:56 UTC, vcloarec commented on src/3d/mesh/qgsmesh3dgeometry_p.cpp
> +  QList<int> facesInExtent = mesh.faceIndexesForRectangle( extent );
`cons`t ?

2023-09-08 08:25 UTC, ptitjano commented on src/3d/mesh/qgsmesh3dgeometry_p.cpp
> +  QList<int> facesInExtent = mesh.faceIndexesForRectangle( extent );
Done.

2023-09-08 08:25 UTC, ptitjano commented on src/3d/mesh/qgsmesh3dgeometry_p.cpp
> +  QList<int> facesInExtent = mesh.faceIndexesForRectangle( extent );
Done.

2023-09-08 08:26 UTC, ptitjano commented on src/3d/mesh/qgsmesh3dentity_p.cpp
> +  mesh->setGeometry( new QgsMeshDataset3DGeometry( mTriangularMesh, layer(), mMapSettings.temporalRange(), mMapSettings.origin(), mMapSettings.extent(), mSymbol.get(), mesh ) );
Indeed.

2023-09-09 11:39 UTC, vcloarec approved these changes

2023-09-11 09:12 UTC, uclaros commented
Nice! Thanks @ptitjano !

2023-09-11 09:17 UTC, uclaros commented
IIRC there's a test for 3d rendering a mesh. Could you also add a test case with limiting the extents?

2023-09-12 09:51 UTC, ptitjano commented
> IIRC there's a test for 3d rendering a mesh. Could you also add a test case with limiting the extents?

Good idea ! Done.

2023-09-12 11:26 UTC, benoitdm-oslandia approved these changes
LGTM

2023-09-19 12:37 UTC, ptitjano commented
@nyalldawson I believe this is ready to be merged. All the requested changes have been made.

2023-09-22 21:34 UTC, merged