Fix for: Skipping blank tiles when creating XYZ tiles #35174
qgis/QGIS pull request #55690
Opened 2023-12-22 08:46 UTC by Soevndahl

## Description

Fix issue #35174 Skipping blank tiles when creating XYZ tiles
When generating tiles, if Skip Empty Tiles is checked, the tiles will not be saved in the directory or in the mbtiles file.
The algorithm is still slow for large areas but this saves space because all empty tiles are not saved.

2023-12-23 15:29 UTC, m-kuhn commented
@alexbruy what do you think about this?

2023-12-25 07:29 UTC, alexbruy requested changes
May I also ask you to squash commits?

As for the comparison of `QImages`, Qt documentation states

> The comparison can be slow, unless there is some obvious difference (e.g. different size or format), in which case the function will return quickly.

So enabling this may make the algorithm much more slower. Maybe consider some other ways to detect empty tiles. In case if we will stick with this approach, I would suggest mentioning expected slowdown in the algorithm help.

2023-12-25 07:29 UTC, alexbruy commented on src/analysis/processing/qgsalgorithmxyztiles.cpp
> +  addParameter( new QgsProcessingParameterBoolean( QStringLiteral( "Skip Empty Tiles" ), QObject::tr( "Skip empty tiles" ), true ) );
We need to stick with parameter naming conventions. Also let's make it optional to keep existing script/models working.

```suggestion
  addParameter( new QgsProcessingParameterBoolean( QStringLiteral( "SKIP_EMPTY_TILES" ), QObject::tr( "Skip empty tiles" ), true, true ) );
```

2023-12-25 07:29 UTC, alexbruy commented on src/analysis/processing/qgsalgorithmxyztiles.cpp
> +  mSkipEmptyTiles = parameterAsBool( parameters, QStringLiteral( "Skip Empty Tiles" ), context );
```suggestion
  mSkipEmptyTiles = parameterAsBool( parameters, QStringLiteral( "SKIP_EMPTY_TILES" ), context );
```

2023-12-25 07:29 UTC, alexbruy commented on src/analysis/processing/qgsalgorithmxyztiles.cpp
> +
Remove extra line

2023-12-25 07:29 UTC, alexbruy commented on src/analysis/processing/qgsalgorithmxyztiles.cpp
> +
Remove extra lines

2023-12-25 07:56 UTC, agiudiceandrea commented
> enabling this may make the algorithm much more slower

It seems the current C++ version (in 3,34) of the algorithm for MBTiles is already much more slower than the Python one (in 3.28) according to https://github.com/qgis/QGIS/issues/55489.

2024-01-24 06:25 UTC, agiudiceandrea commented
@Soevndahl , please have a look at the requested changes.

2024-02-09 12:08 UTC, m-kuhn commented on src/analysis/processing/qgsalgorithmxyztiles.cpp
> +  addParameter( new QgsProcessingParameterBoolean( QStringLiteral( "Skip_Empty_Tiles" ), QObject::tr( "Skip empty tiles" ), true, true ) );
```suggestion
  addParameter( new QgsProcessingParameterBoolean( QStringLiteral( "SKIP_EMPTY_TILES" ), QObject::tr( "Skip empty tiles" ), true, true ) );
```

let's be consistent with capitalization

2024-02-09 12:08 UTC, m-kuhn commented on src/analysis/processing/qgsalgorithmxyztiles.cpp
> +  mSkipEmptyTiles = parameterAsBool( parameters, QStringLiteral( "Skip_Empty_Tiles" ), context );
```suggestion
  mSkipEmptyTiles = parameterAsBool( parameters, QStringLiteral( "SKIP_EMPTY_TILES" ), context );
```

2024-02-19 16:27 UTC, agiudiceandrea commented
@Soevndahl , please have a look at the requested changes.

2024-03-12 02:33 UTC, closed without merging