qgsrectangle: Properly handle NaN coordinates in intersects method
qgis/QGIS pull request #58346
Opened 2024-08-08 17:45 UTC by ptitjano

## Description

This brings two changes to the `intersects` method of `QgsRectangle`: 
- if one of the rectangles contains only `NaN` coordinate, intersects now returns `false`
- if one of the rectangles contains at least one `NaN` coordinate, intersects now returns `false`

2024-08-12 06:40 UTC, uclaros commented
> * if one of the rectangles contains at least one `NaN` coordinate, intersects now returns `false`

If you check for _any_ first, there's no need to check for _all_ too!

But then again, if _any_ ordinate in a `QgsRectangle` is `NaN`, shouldn't `isNull() == true`?

2024-08-12 07:15 UTC, ptitjano commented
> > * if one of the rectangles contains at least one `NaN` coordinate, intersects now returns `false`
> 
> If you check for _any_ first, there's no need to check for _all_ too!
> 

I did so, because I was expecting a reply like "you need to drop the second commit, it doesn't respect the existing logic of `isNull` which needs all coordinates to be `Nan`.

The logic of "all coordinates need to be NaN if This was added this way in `QgsRectangle` because this was already did this way in `QgsBox3D`.  

> But then again, if _any_ ordinate in a `QgsRectangle` is `NaN`, shouldn't `isNull() == true`?

Is that your opinion or you just ask the question?

2024-08-27 12:26 UTC, benoitdm-oslandia requested changes

2024-08-27 12:26 UTC, benoitdm-oslandia commented on src/core/geometry/qgsrectangle.h
> +      if ( std::isgreater( x1, x2 ) || std::isnan( x1 ) || std::isnan( x2 ) )
```suggestion
      if ( std::isnan( x1 ) || std::isnan( x2 )  || std::isgreater( x1, x2 ) )
```

2024-08-27 12:26 UTC, benoitdm-oslandia commented on src/core/geometry/qgsrectangle.h
> +      const double x1 = ( ( std::isgreater( mXmin, rect.mXmin ) || std::isnan( mXmin ) ) ? mXmin : rect.mXmin );
as the if eval start with the left most expression, I would have like that: 

```suggestion
      const double x1 = ( ( std::isnan( mXmin ) || std::isgreater( mXmin, rect.mXmin ) ) ? mXmin : rect.mXmin );
```

2024-08-27 12:26 UTC, benoitdm-oslandia commented on src/core/geometry/qgsrectangle.h
> +      const double x2 = ( ( std::isless( mXmax, rect.mXmax ) || std::isnan( mXmax ) )  ? mXmax : rect.mXmax );
```suggestion
      const double x2 = ( ( std::isnan( mXmax ) || std::isless( mXmax, rect.mXmax ) )  ? mXmax : rect.mXmax );
```

2024-08-27 12:26 UTC, benoitdm-oslandia commented on src/core/geometry/qgsrectangle.h
> +      const double y1 = ( ( std::isgreater( mYmin, rect.mYmin ) || std::isnan( mYmin ) ) ? mYmin : rect.mYmin );
```suggestion
      const double y1 = ( ( std::isnan( mYmin ) || std::isgreater( mYmin, rect.mYmin ) ) ? mYmin : rect.mYmin );
```

2024-08-27 12:26 UTC, benoitdm-oslandia commented on src/core/geometry/qgsrectangle.h
> +      const double y2 = ( ( std::isless( mYmax, rect.mYmax ) || std::isnan( mYmax ) ) ? mYmax : rect.mYmax );
```suggestion
      const double y2 = ( ( std::isnan( mYmax ) || std::isless( mYmax, rect.mYmax ) ) ? mYmax : rect.mYmax );
```

2024-08-27 12:26 UTC, benoitdm-oslandia commented on src/core/geometry/qgsrectangle.h
> +      return ( std::islessequal( y1, y2 ) && !std::isnan( y1 ) && !std::isnan( y2 ) );
```suggestion
      return ( !std::isnan( y1 ) && !std::isnan( y2 ) && std::islessequal( y1, y2 ) );
```

2024-08-27 14:34 UTC, uclaros commented
> Is that your opinion or you just ask the question?

Both I guess! :)

Can you think of a case where it makes sense for `isNull()` to return `false` while an ordinate is `NaN`?
I am not sure about the implications of such a change, but it makes sense to me!

2024-09-03 18:18 UTC, ptitjano commented
> > Is that your opinion or you just ask the question?
> 
> Both I guess! :)
> 
> Can you think of a case where it makes sense for `isNull()` to return `false` while an ordinate is `NaN`? I am not sure about the implications of such a change, but it makes sense to me!

The `NaN` values for `QgsRectangle` were introduced in QGIS 3.38 by @benoitdm-oslandia. Therefore, it's quite recent and we don't need to worry about breaking a legacy behavior. 

Indeed, the main question is: should we consider a `QgsRectangle` as null if at least one coordinate is a `NaN`? @benoitdm-oslandia @lbartoletti what do you think?

2024-09-04 05:47 UTC, benoitdm-oslandia commented
As we do not have a `isValid` function, I think `isNull` should return false if there is any NaN value.

2024-09-04 06:41 UTC, lbartoletti commented
> As we do not have a `isValid` function, I think `isNull` should return false if there is any NaN value.

Or create a distinct `isValid` function.

I think, we should distinguish between two separate functions:

1. `isNull()`:
   - Returns `true` only if all coordinates are NaN values.
   - Indicates that a rectangle has not been defined yet or has been explicitly initialized as null.

2. `isValid()`:
   - Should be a distinct function from `isNull()`.
   - Returns `false` if any coordinate is NaN or infinite.
   - Checks if the rectangle is well-defined and usable for calculations.


A rectangle can be created "empty" (thus null) or defined (thus not null) but invalid if one or more of its coordinates are NaN or infinite, for example, due to a calculation error.

Having both functions, well-explained, can be beneficial as seen in several codebases using this "double" check approach.

2024-09-04 13:48 UTC, lbartoletti commented
Nice, thanks for this first part.

2024-09-04 13:48 UTC, lbartoletti approved these changes

2024-09-04 13:48 UTC, merged