fix running algs with virtual layers
qgis/QGIS pull request #59985
Opened 2024-12-20 08:37 UTC by NyakudyaA

Fixes https://github.com/qgis/QGIS/issues/59364

Resurrects https://github.com/qgis/QGIS/pull/59465

2025-01-06 06:33 UTC, NyakudyaA commented
not stale

2025-01-08 13:52 UTC, elpaso commented on python/plugins/processing/algs/gdal/Buffer.py
> +        if not source_details.layer_name:
Are these changes (and all the others below, except the virtual layers part) related to the PR title "fix running gdal algs with virtual layers"  ?

2025-01-08 15:01 UTC, NyakudyaA commented on python/plugins/processing/algs/gdal/Buffer.py
> +        if not source_details.layer_name:
Yes

2025-01-23 06:47 UTC, NyakudyaA commented
Not stale

2025-02-03 00:25 UTC, nyalldawson requested changes

2025-02-03 00:25 UTC, nyalldawson commented on python/plugins/processing/algs/gdal/GdalAlgorithmDialog.py
> +                    parameters, context, feedback, executing=True
This is wrong -- we are NOT executing here, so the existing code is correct and should not be changed

2025-02-03 00:25 UTC, nyalldawson commented on python/plugins/processing/algs/gdal/ogr2ogr.py
> +            )
This should be after we've set convertAllLayers, and the condition should be:

    if not convertAllLayers and not input_details.layer_name:

2025-02-03 00:25 UTC, nyalldawson commented on python/plugins/processing/algs/gdal/ogr2ogrtopostgislist.py
> +        if not input_details.layer_name:
This algorithm looks tolerant to empty layer names, so let's be safe:
```suggestion
        if input_details.layer_name is None:
```

2025-02-03 00:25 UTC, nyalldawson commented on python/plugins/processing/algs/gdal/GdalAlgorithm.py
> +                    geometry_column_name="geom",
Also set for the else: branch here

2025-02-24 02:48 UTC, closed without merging

2025-02-24 06:49 UTC, NyakudyaA commented
Not stale