[snapping] fix missing layers in snapping config dialog (fixes #17792)
qgis/QGIS pull request #6026
Opened 2018-01-10 05:18 UTC by nirvn

## Description
We have a regression in master whereas the snapping configuration dialog doesn't show project layers when a project has been loaded. If a layer is added / deleted subsequently to reading a project, all the layers appear.

@m-kuhn , @wonder-sk , @nyalldawson , I'm not sure if this is the right way to fix the referred issue, but it works 😉 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

2018-01-10 15:06 UTC, 3nids requested changes
I'm not sure this is the appropriate approach.

QgsLayerTreeModel should get correctly updated without the need to recreate it.

It (the QgsLayerTreeModel) is the source model of the QgsSnappingLayerTreeModel (QSortFilterProxyModel).

It sounds to me that some info is not propagated correctly: the snapping model doesn't know about the complete reset of the layer tree model.

Although your fix might work, I would be in favor to fix this down to the layer tree model to avoid a similar issue in another scenario.

2018-01-11 01:00 UTC, nirvn commented
@3nids , I think what's happening here is that as the project loads n build its layer tree, the added layers can't be resolved into pointers to layers (at the time the snapping model register those) and we end up with a blank list.

That said, I haven't been able to come up with a better fix than this bandaid yet.

2018-01-11 01:02 UTC, nirvn commented
If you have the snapping config open with an empty list, you can try to uncheck n recheck a layer in your loaded project, you'll see it appearing in the snapping config (with remaining layers missing).

2018-01-11 04:34 UTC, nirvn commented
Alright, the code is now resetting the source model instead of replacing it, hope this is better. 

I've also had to move the `emit snappingConfigChanged( mSnappingConfig );` signal to occur _after_ the projectRead signal, otherwise the advanced snapping settings wouldn't apply (an unreported issue).

2018-01-11 12:17 UTC, nirvn commented
@3nids , let me know if you think the updated approach is any better.

2018-01-11 12:50 UTC, 3nids reviewed
Thanks a lot for the followup.
This does sounds better to me.
I would prefer to have a wiser mind (@wonder-sk or @m-kuhn) to validate the approach but without being able to bring a further understanding, LGTM.

2018-01-11 12:50 UTC, 3nids approved these changes

2018-01-11 12:52 UTC, 3nids commented
I'm not being exhaustive for the wiser minds... I just quoted those involved in the legend. No offense to the others ;)

2018-01-12 08:26 UTC, nirvn commented
If nobody objects to this, I'll merge the PR later this afternoon. Thanks.

2018-01-12 09:17 UTC, merged