[layout] Automatic conversion of 2.x composition templates to layouts
qgis/QGIS pull request #6470
Opened 2018-02-26 18:02 UTC by elpaso

2018-02-26 23:58 UTC, nyalldawson requested changes
Looking great! 

Please check expected_importComposerTemplateMap_0_mask.png -- I think it's been updated with the wrong reference image and is now passing any image.

2018-02-26 23:58 UTC, nyalldawson commented on src/core/layout/qgscompositionconverter.h
> +     * \param document a dom document
Drop this param annotation - it's not providing any new info

2018-02-26 23:58 UTC, nyalldawson commented on src/core/layout/qgscompositionconverter.h
> +     */
\since QGIS 3.0.1

2018-02-27 08:36 UTC, elpaso commented
Yes, I noticed and triple checked the wierd mask yesterday evening but I couldn't figure out where the problem was.  I'll give it another fresh look.

2018-02-27 09:12 UTC, nyalldawson commented
Looks good! +1 to merge if Travis approves

2018-02-27 09:14 UTC, merged