Fixes #20064: Bug in Server WFS update transaction
qgis/QGIS pull request #8155
Opened 2018-10-09 21:12 UTC by uprel

## Description
Fixing bug in update transaction to check for one or more Property elements. Should throw exception if there are none Property elements and not when it is not one.
Link to issue https://issues.qgis.org/issues/20064

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

2018-10-10 08:04 UTC, elpaso commented
LGTM but can you please amend the commit message to something more meaningful than "Fixes"?

2018-10-10 09:22 UTC, uprel commented
Sorry for that. I was commiting over command line and put message without "", so it was stripped...

2018-10-16 09:30 UTC, uprel commented
@rldhont can you please take time to look at this issue and proposed fix. WFS-transactions now are broken if you are sending more then one attribute update. Easy test is with QGIS connect as WFS-client and modify  only one attribute works, but when you modify two or more it doesn't work.
I couldn't test the fix because I don't have running environment setup, but I wish to test it from the nightly  builds.

2018-10-16 11:40 UTC, rldhont approved these changes

2018-10-16 11:41 UTC, uprel commented
thanks @rldhont , please merge someone.

2018-10-16 11:43 UTC, rldhont requested changes
Can you do a `git commit --amend` to update the commit message to be as descriptive as possible and `git push -f` to force update your remote branch.

Thanks.

2018-10-16 13:49 UTC, uprel commented
Done, just adding new log message as suggested by @rldhont .

2018-10-16 17:11 UTC, merged

2018-10-23 14:05 UTC, uprel commented
This is now fixed for WFS 1.1.0 in master (tested). Just realized there is own file for WFS 1.0.0 where there is same part of code and same problem. What do you think, @rldhont and @elpaso, should I do another PR for this line?

https://github.com/qgis/QGIS/blob/daf53940421de07a5daf7e419cfbf06826ad2469/src/server/services/wfs/qgswfstransaction_1_0_0.cpp#L1074

2018-10-23 14:18 UTC, elpaso commented
Yes please