[needs-docs] Fixes #18466: Switch Add and Close buttons
qgis/QGIS pull request #8156
Opened 2018-10-09 23:55 UTC by JamesShaeffer

## Description
Updated the Add button type in the Add Layer dialog window from 'Accept' to 'Ok' to fix the order of buttons in Windows.

## Checklist
- [X] Commit messages are descriptive and explain the rationale for changes
- [X] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [X] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [X] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

2018-10-10 07:46 UTC, elpaso requested changes
Apply role is correct here because the dialog is not closed.

2018-10-10 19:52 UTC, JamesShaeffer commented
Testing on my workstation shows that dialog window does not close after a layer is added and remains open for further layers to be added.

2018-10-11 05:53 UTC, elpaso commented
> Testing on my workstation shows that dialog window does not close after a layer is added and remains open for further layers to be added.

That's exactly what I'm saying: the "Apply" role is the correct role for applying changes without closing a dialog, "Ok" role is not.

2018-10-11 18:50 UTC, JamesShaeffer commented
I guess I wasn't clear in my response. The change in role from 'Apply' to 'Ok' appears to not change the functionality and that clicking the 'Add Layer' button, with its newly changed role, simply adds the layer while keeping the dialog window open.

2018-10-11 20:06 UTC, elpaso commented
Sorry, I wasn't clear either, the implementation in Qt is that in order to have the "right" order of the buttons according to UX guidelines of the various platforms (windows, OSX, Linux etc.) you assign "roles" to buttons, this makes sure that you have a consistent GUI/UX across the application and the operating system.

We have two actions (not counting help and additional provider buttons here):

1. apply the changes by adding the layer
2. close the dialog

And these would be roles for buttons associated with those actions:
Apply role = action 1
Close role = action 2
Ok role = action 1 followed by action 2  <-- we don't have this one!

When you click the "Add" button you are actually applying the changes  (action 1: a layer is added to the legend and the canvas) without closing the dialog (action 2), and this is exactly the "apply" role, I changed the button name from "Apply" (the standard name) to "Add" because the action is to "add" a layer and it seemed more intuitive to me, but the button role is exactly the one of an "Apply" button and it's **not** the role of an Ok button as in your proposed change.

2018-10-16 04:15 UTC, nyalldawson commented
I gather this is a wontfix -- let's close?

2018-10-16 07:27 UTC, closed without merging

2018-10-16 12:44 UTC, Gustry commented
The good patch would be to fix the order, not the button role. I agree with the purpose of this PR, the reordering of buttons. It's not logical IIRC on some OS.

2018-10-16 13:08 UTC, DelazJ commented
On Windows, I often click on close instead of Add. Luckily the dialog is not cleared each time it's closed otherwise... 
>When you click the "Add" button you are actually applying the changes (action 1: a layer is added to the legend and the canvas) without closing the dialog (action 2), and this is exactly the "apply" role, I changed the button name from "Apply" (the standard name) to "Add" because the action is to "add" a layer and it seemed more intuitive to me, but the button role is exactly the one of an "Apply" button and it's not the role of an Ok button as in your proposed change.

I think that we understand and agree with this logic (keeping two buttons) but what I understand from @JamesShaeffer comment (and I did/can not test it!) is that even using the OK role, the dialog is kept open instead of closing as it should normally do. Hence we have "right" order and right behavior.

2018-10-16 13:14 UTC, elpaso commented
We do not want to use the OK role for a button that does not have the behavior of an OK button but has the behavior of an "Apply" button, do we?

For the order of buttons, we follow Qt system: http://doc.qt.io/qt-5/qdialogbuttonbox.html#details Qt library takes care of ordering the buttons automatically according to UX/UI  guidelines of the operating system.

We should normally avoid to order buttons explicitly (for "standard" buttons I mean).

2018-10-16 13:55 UTC, DelazJ commented
> If you are talking about changing the "Add" button role to an OK button (and hence close the dialog) that topic has been already discussed a lot, there was not 100% consent though, but a decision was made, of course it can be discussed again, see the original PR for a loooong discussion about the button roles, behaviors, names and positions.

Not at all. I'm aware of this discussion and prefer to keep the dialog open after I add layers. I just wanted to stress that @JamesShaeffer comment did not contradict yours. But I agree with 
> We do not want to use the OK role for a button that does not have the behavior of an OK button but has the behavior of an "Apply" button, do we?

Anyway, looks like I'm less used to the "apply-roled" button and I have to learn it. Never notice they were placed at the right of the reject ones.

2018-10-16 14:12 UTC, Gustry commented
https://issues.qgis.org/issues/18466
https://issues.qgis.org/issues/19002
for reference