add the -te and -te_srs and -multi parameters to the gdalwarp tool used to clip rasters by mask layers
qgis/QGIS pull request #8445
Opened 2018-11-08 18:55 UTC by gioman

## Description

Those parameters are already implemented in the "warp" tool, as the clip raster by mask layer also uses gdalwarp it makes sense to have them in both tools. Fixes: https://issues.qgis.org/issues/20415

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

2018-11-08 21:54 UTC, luipir commented
@gioman please add related test in https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/GdalAlgorithmsTest.py#L520 e.g. how the command string should be produced when the new parameters are set.... and fix python indentationthat fail travis, e.g. run preparecommit script before to commit.

2018-11-08 21:55 UTC, luipir requested changes
add test as described and fix python indentation

2018-11-12 20:08 UTC, luipir approved these changes

2018-11-12 20:09 UTC, luipir commented
@gioman any chance to add a test? for gdal is really simple!

2018-11-12 20:12 UTC, gioman commented
> @gioman any chance to add a test? for gdal is really simple!

Yes Luigi, of course. I just miss the time right now (same for the other PR I made recently). But I will do.

2018-12-04 10:32 UTC, luipir commented
IMHO to be merged and leave test creation to @gioman during next hackfest.. he have to learn how to do

2018-12-04 10:32 UTC, merged

2018-12-06 09:47 UTC, gioman commented
> IMHO to be merged and leave test creation to @gioman during next hackfest.. he have to learn how to do

@luipir thanks. I agree :)