Give more information when errors opening zip happens
qgis/QGIS pull request #9177
Opened 2019-02-14 12:23 UTC by mbernasocchi

## Description
When opening a QGZ file and something goes wrong this should give us the libzip error to see what went wrong. 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

2019-02-14 12:47 UTC, luipir requested changes
would be better to use a the rc string code instead of a enum? you can obtain using something like https://libzip.org/documentation/zip_error_to_str.html

2019-02-17 15:43 UTC, m-kuhn commented
@luipir I think the `zip_strerror` on the same line already does that.
@mbernasocchi can you provide some minimal information on what's not sufficient in the `zip_strerror` string / added value from the return code?

The minimal change request I'd have for this PR is to remove capitalization on `ERROR`.

2019-02-17 19:43 UTC, luipir commented
> @luipir I think the `zip_strerror` on the same line already does that.

ouch! I need mor eyes!

2019-02-18 06:42 UTC, mbernasocchi commented
@m-kuhn the issue is that when `z` evaluates to false we get only the `zipFilename` without getting more information on what when wrong on the libzip side

2019-02-18 09:17 UTC, merged